"""niconico support for Music Assistant."""

from __future__ import annotations

from typing import TYPE_CHECKING

from music_assistant_models.config_entries import (
    ConfigEntry,
    ConfigValueOption,
    ConfigValueType,
    ProviderConfig,
)
from music_assistant_models.enums import (
    ConfigEntryType,
)

from music_assistant.constants import (
    CONF_PASSWORD,
    CONF_USERNAME,
)
from music_assistant.mass import MusicAssistant
from music_assistant.models import ProviderInstanceType
from music_assistant.providers.niconico.constants import (
    CONF_MFA,
    CONF_SENSITIVE_CONTENTS,
    CONF_USER_SESSION,
)
from music_assistant.providers.niconico.provider import NiconicoMusicProvider

if TYPE_CHECKING:
    from music_assistant_models.provider import ProviderManifest


async def setup(
    mass: MusicAssistant, manifest: ProviderManifest, config: ProviderConfig
) -> ProviderInstanceType:
    """Initialize provider(instance) with given configuration."""
    return NiconicoMusicProvider(mass, manifest, config)


async def get_config_entries(
    mass: MusicAssistant,  # noqa: ARG001
    instance_id: str | None = None,  # noqa: ARG001
    action: str | None = None,  # noqa: ARG001
    values: dict[str, ConfigValueType] | None = None,  # noqa: ARG001
) -> tuple[ConfigEntry, ...]:
    """
    Return Config entries to setup this provider.

    instance_id: id of an existing provider instance (None if new instance setup).
    action: [optional] action key called from config entries UI.
    values: the (intermediate) raw values for config entries sent with the action.
    """
    return (
        ConfigEntry(key=CONF_USERNAME, type=ConfigEntryType.STRING, label="Mail", required=False),
        ConfigEntry(
            key=CONF_PASSWORD,
            type=ConfigEntryType.SECURE_STRING,
            label="Password",
            required=False,
            description="The Login password.",
        ),
        ConfigEntry(
            key=CONF_MFA,
            type=ConfigEntryType.STRING,
            label="MFA Code(one time password)",
            required=False,
            description=(
                "Enter the 6-digit confirmation code generated by your 2-step "
                "verification app (e.g., Google Authenticator)."
            ),
        ),
        ConfigEntry(
            key=CONF_USER_SESSION,
            type=ConfigEntryType.SECURE_STRING,
            label="User Session(cookie)",
            required=False,
            description=(
                "Enter the user_session obtained from the cookie."
                "If invalid, it will be set automatically from your email and password."
            ),
        ),
        ConfigEntry(
            key=CONF_SENSITIVE_CONTENTS,
            type=ConfigEntryType.STRING,
            label="Sensitive Content Handling",
            required=False,
            default_value=None,
            options=[
                ConfigValueOption(title="Default (No filtering)", value=None),
                ConfigValueOption(title="Mask sensitive content", value="mask"),
                ConfigValueOption(title="Filter out sensitive content", value="filter"),
            ],
            description=(
                "Choose how to handle sensitive content in searches and recommendations. "
                "'Mask' will show sensitive content with warnings, "
                "'Filter' will hide it completely."
            ),
            category="content",
        ),
    )
