"""niconico support for Music Assistant."""

from __future__ import annotations

import asyncio
from collections.abc import AsyncGenerator, Callable
from io import StringIO
from typing import TYPE_CHECKING, Any, TypeVar, cast

from music_assistant_models.config_entries import (
    ConfigEntry,
    ConfigValueType,
    ProviderConfig,
)
from music_assistant_models.enums import (
    ConfigEntryType,
    ContentType,
    ImageType,
    MediaType,
    ProviderFeature,
    StreamType,
)
from music_assistant_models.errors import (
    LoginFailed,
    MediaNotFoundError,
    UnplayableMediaError,
)
from music_assistant_models.media_items import (
    Album,
    Artist,
    AudioFormat,
    MediaItemImage,
    MediaItemMetadata,
    MediaItemType,
    Playlist,
    ProviderMapping,
    RecommendationFolder,
    SearchResults,
    Track,
)
from music_assistant_models.streamdetails import StreamDetails
from music_assistant_models.unique_list import UniqueList
from niconico import NicoNico
from niconico.objects.video import EssentialVideo, Owner
from niconico.objects.video.search import EssentialMylist, EssentialSeries
from yt_dlp import YoutubeDL

from music_assistant.constants import (
    CACHE_CATEGORY_LIBRARY_ITEMS,
    CONF_PASSWORD,
    CONF_USERNAME,
)
from music_assistant.helpers.throttle_retry import ThrottlerManager
from music_assistant.mass import MusicAssistant
from music_assistant.models import ProviderInstanceType
from music_assistant.models.music_provider import MusicProvider

if TYPE_CHECKING:
    from music_assistant_models.provider import ProviderManifest
    from niconico.objects.user import (
        NicoUser,
        UserMylistItem,
    )
    from niconico.objects.video import Mylist
    from requests.cookies import RequestsCookieJar

T = TypeVar("T")

CONF_MAIL = "mail"
CONF_MFA = "mfa"

NICONICO_COOKIE_DOMAIN = ".nicovideo.jp"

niconico_api_throttler = ThrottlerManager(rate_limit=1, period=2)


async def setup(
    mass: MusicAssistant, manifest: ProviderManifest, config: ProviderConfig
) -> ProviderInstanceType:
    """Initialize provider(instance) with given configuration."""
    # setup is called when the user wants to setup a new provider instance.
    # you are free to do any preflight checks here and but you must return
    #  an instance of the provider.
    return NiconicoMusicprovider(mass, manifest, config)


async def get_config_entries(
    mass: MusicAssistant,  # noqa: ARG001
    instance_id: str | None = None,  # noqa: ARG001
    action: str | None = None,  # noqa: ARG001
    values: dict[str, ConfigValueType] | None = None,  # noqa: ARG001
) -> tuple[ConfigEntry, ...]:
    """
    Return Config entries to setup this provider.

    instance_id: id of an existing provider instance (None if new instance setup).
    action: [optional] action key called from config entries UI.
    values: the (intermediate) raw values for config entries sent with the action.
    """
    return (
        ConfigEntry(key=CONF_USERNAME, type=ConfigEntryType.STRING, label="Mail", required=True),
        ConfigEntry(
            key=CONF_PASSWORD,
            type=ConfigEntryType.SECURE_STRING,
            label="Password",
            required=True,
            description="The Login password.",
        ),
        ConfigEntry(
            key=CONF_MFA,
            type=ConfigEntryType.STRING,
            label="MFA Code(one time password)",
            required=False,
            description=(
                "Enter the 6-digit confirmation code generated by your 2-step "
                "verification app (e.g., Google Authenticator)."
            ),
        ),
    )


class NiconicoMusicprovider(MusicProvider):
    """Niconico music provider for Music Assistant."""

    @property
    def supported_features(self) -> set[ProviderFeature]:
        """Return the features supported by this Provider."""
        # MANDATORY
        # you should return a tuple of provider-level features
        # here that your player provider supports or an empty tuple if none.
        # for example 'ProviderFeature.SYNC_PLAYERS' if you can sync players.
        return {
            ProviderFeature.SEARCH,
            ProviderFeature.LIBRARY_TRACKS,
            ProviderFeature.LIBRARY_PLAYLISTS,
            ProviderFeature.LIBRARY_ARTISTS,
            ProviderFeature.ARTIST_TOPTRACKS,
            # see the ProviderFeature enum for all available features
        }

    async def handle_async_init(self) -> None:
        """Handle async initialization of the provider."""
        await self.try_logout()
        self.niconico_py_client = NicoNico()
        await self.try_login()
        # Schedule periodic re-login to refresh the session
        self.mass.create_task(self._schedule_periodic_relogin())

    async def _schedule_periodic_relogin(self) -> None:
        """Periodically re-login to refresh the session."""
        while True:
            await asyncio.sleep(30 * 24 * 60 * 60)  # Wait for 30 days
            self.logger.info("Performing periodic re-login to refresh the session.")
            await self.try_logout()
            await self.try_login()

    async def unload(self, is_removed: bool = False) -> None:
        """
        Handle unload/close of the provider.

        Called when provider is deregistered (e.g. MA exiting or config reloading).
        is_removed will be set to True when the provider is removed from the configuration.
        """
        await self.try_logout()

    @property
    def is_streaming_provider(self) -> bool:
        """
        Return True if the provider is a streaming provider.

        This literally means that the catalog is not the same as the library contents.
        For local based providers (files, plex), the catalog is the same as the library content.
        It also means that data is if this provider is NOT a streaming provider,
        data cross instances is unique, the catalog and library differs per instance.

        Setting this to True will only query one instance of the provider for search and lookups.
        Setting this to False will query all instances of this provider for search and lookups.
        """
        # For streaming providers return True here but for local file based providers return False.
        return True

    async def search(
        self,
        search_query: str,
        media_types: list[MediaType],
        limit: int = 5,
    ) -> SearchResults:
        """Perform search on musicprovider.

        :param search_query: Search query.
        :param media_types: A list of media_types to include.
        :param limit: Number of items to return in the search (per type).
        """
        search_result = SearchResults()

        if MediaType.TRACK in media_types:
            await self.search_videos_by_keyword(search_query, limit, search_result)

        if MediaType.PLAYLIST in media_types:
            await self.search_playlists_by_keyword(search_query, limit, search_result)

        return search_result

    async def search_playlists_by_keyword(
        self, search_query: str, limit: int, search_result: SearchResults
    ) -> None:
        """Search for playlists by keyword."""
        mylist_search_data = await call_with_throttler(
            self.niconico_py_client.video.search.search_lists,
            search_query,
            page_size=limit,
            types=["mylist"],
        )
        if mylist_search_data:
            search_result.playlists = []
            item: EssentialMylist | EssentialSeries
            for item in mylist_search_data.items:
                if isinstance(item, EssentialMylist):
                    search_result.playlists.append(_parse_playlist_by_mylist(self, item))

    async def search_videos_by_keyword(
        self, search_query: str, limit: int, search_result: SearchResults
    ) -> None:
        """Search for videos by keyword."""
        video_search_data = await call_with_throttler(
            self.niconico_py_client.video.search.search_videos_by_keyword,
            search_query,
            page_size=limit,
        )
        if video_search_data:
            search_result.tracks = []
            for item in video_search_data.items:
                if isinstance(item, EssentialVideo):
                    track = _parse_track_by_essential_video(self, item)
                    if track:
                        search_result.tracks.append(track)

    async def get_library_artists(self) -> AsyncGenerator[Artist, None]:
        """Retrieve library artists from the provider."""
        library_item_ids = await self.mass.cache.get(
            "track",
            category=CACHE_CATEGORY_LIBRARY_ITEMS,
            base_key=self.instance_id,
        )
        if not library_item_ids:
            return

        library_item_ids = cast("list[int]", library_item_ids)
        query = "tracks.item_id in :ids"
        query_params = {"ids": library_item_ids}
        tracks = await self.mass.music.tracks.library_items(
            extra_query=query, extra_query_params=query_params
        )

        for track in tracks:
            for artist in track.artists:
                if isinstance(artist, Artist):
                    yield artist

    # TODO: Use "series" as a albums.
    async def get_library_albums(self) -> AsyncGenerator[Album, None]:
        """Retrieve library albums from the provider."""
        yield  # type: ignore[misc]

    async def get_library_tracks(self) -> AsyncGenerator[Track, None]:
        """Retrieve library tracks from the provider."""
        if not self.is_logged_in():
            return

        library_item_ids = await self.mass.cache.get(
            "playlist",
            category=CACHE_CATEGORY_LIBRARY_ITEMS,
            base_key=self.instance_id,
        )
        if not library_item_ids:
            return

        library_item_ids = cast("list[int]", library_item_ids)
        query = "playlists.item_id in :ids"
        query_params = {"ids": library_item_ids}
        playlists = await self.mass.music.playlists.library_items(
            extra_query=query, extra_query_params=query_params
        )

        for playlist in playlists:
            page = 0
            prov_map = next(iter(playlist.provider_mappings), None)
            if not prov_map:
                continue

            while True:
                playlist_tracks = await self.get_playlist_tracks(prov_map.item_id, page)
                if not playlist_tracks:
                    break

                for track in playlist_tracks:
                    yield track

                page += 1

    # Use "mylist" as a playlist.
    async def get_library_playlists(self) -> AsyncGenerator[Playlist, None]:
        """Retrieve library/subscribed playlists from the provider."""
        if not self.is_logged_in():
            return

        results: list[UserMylistItem] = await call_with_throttler(
            self.niconico_py_client.user.get_own_mylists
        )
        for entry in results:
            yield _parse_playlist_by_mylist(self, entry)

    async def get_artist(self, prov_artist_id: str) -> Artist:
        """Get full artist details by id."""
        user = await call_with_throttler(self.niconico_py_client.user.get_user, prov_artist_id)
        if not user:
            raise MediaNotFoundError(f"Artist with id {prov_artist_id} not found on Niconico.")
        return _parse_artist(self, user)

    async def get_artist_albums(self, prov_artist_id: str) -> list[Album]:  # type: ignore[empty-body]
        """Get a list of all albums for the given artist."""

    async def get_artist_toptracks(self, prov_artist_id: str) -> list[Track]:
        """Get a list of most popular tracks for the given artist."""
        all_tracks = []
        page = 0
        while True:
            user_video_data = await call_with_throttler(
                self.niconico_py_client.user.get_user_videos,
                prov_artist_id,
                page=page,
                page_size=500,
            )
            if not user_video_data or not user_video_data.items:
                break

            for item in user_video_data.items:
                track = _parse_track_by_essential_video(self, item.essential)
                all_tracks.append(track)

            page += 1
        return all_tracks

    async def get_album(self, prov_album_id: str) -> Album:  # type: ignore[empty-body]
        """Get full album details by id."""
        # Get full details of a single Album.
        # Mandatory only if you reported LIBRARY_ALBUMS in the supported_features.

    async def get_track(self, prov_track_id: str) -> Track:
        """Get full track details by id."""
        # Get full details of a single Track.
        # Mandatory only if you reported LIBRARY_TRACKS in the supported_features.
        video = await call_with_throttler(self.niconico_py_client.video.get_video, prov_track_id)
        if not video:
            raise MediaNotFoundError(f"Track with id {prov_track_id} not found on Niconico.")
        return _parse_track_by_essential_video(self, video)

    async def get_playlist(self, prov_playlist_id: str) -> Playlist:
        """Get full playlist details by id."""
        mylist: Mylist | None = await call_with_throttler(
            self.niconico_py_client.video.get_mylist, prov_playlist_id, page_size=500
        )

        if not mylist:
            mylist = await call_with_throttler(
                self.niconico_py_client.user.get_own_mylist, prov_playlist_id, page_size=500
            )

        if not mylist:
            raise MediaNotFoundError(f"Playlist with id {prov_playlist_id} not found on Niconico.")

        return _parse_playlist_by_mylist(self, mylist)

    async def get_album_tracks(  # type: ignore[empty-body]
        self,
        prov_album_id: str,
    ) -> list[Track]:
        """Get album tracks for given album id."""
        # Get all tracks for a given album.
        # Mandatory only if you reported ARTIST_ALBUMS in the supported_features.

    async def get_playlist_tracks(
        self,
        prov_playlist_id: str,
        page: int = 0,
    ) -> list[Track]:
        """Get all playlist tracks for given playlist id."""
        # Get all tracks for a given playlist.
        # Mandatory only if you reported LIBRARY_PLAYLISTS in the supported_features.
        mylist: Mylist | None = await call_with_throttler(
            self.niconico_py_client.video.get_mylist, prov_playlist_id, page_size=500, page=page + 1
        )

        if not mylist:
            mylist = await call_with_throttler(
                self.niconico_py_client.user.get_own_mylist,
                prov_playlist_id,
                page_size=500,
                page=page + 1,
            )

        if not mylist:
            return []

        tracks = []
        for item in mylist.items:
            track = _parse_track_by_essential_video(self, item.video)
            tracks.append(track)
        return tracks

    async def library_add(self, item: MediaItemType) -> bool:
        """Add item to provider's library. Return true on success."""
        # Add an item to your provider's library.
        # This is only called if the provider supports the EDIT feature for the media type.
        return True

    async def library_remove(self, prov_item_id: str, media_type: MediaType) -> bool:
        """Remove item from provider's library. Return true on success."""
        # Remove an item from your provider's library.
        # This is only called if the provider supports the EDIT feature for the media type.
        return True

    async def add_playlist_tracks(self, prov_playlist_id: str, prov_track_ids: list[str]) -> None:
        """Add track(s) to playlist."""
        # Add track(s) to a playlist.
        # This is only called if the provider supports the PLAYLIST_TRACKS_EDIT feature.

    async def remove_playlist_tracks(
        self, prov_playlist_id: str, positions_to_remove: tuple[int, ...]
    ) -> None:
        """Remove track(s) from playlist."""
        # Remove track(s) from a playlist.
        # This is only called if the provider supports the PLAYLIST_TRACKS_EDIT feature.

    async def create_playlist(self, name: str) -> Playlist:  # type: ignore[empty-body]
        """Create a new playlist on provider with given name."""
        # Create a new playlist on the provider.
        # This is only called if the provider supports the PLAYLIST_CREATE feature.

    async def get_similar_tracks(  # type: ignore[empty-body]
        self, prov_track_id: str, limit: int = 25
    ) -> list[Track]:
        """Retrieve a dynamic list of similar tracks based on the provided track."""
        # Get a list of similar tracks based on the provided track.
        # This is only called if the provider supports the SIMILAR_TRACKS feature.

    async def get_stream_details(self, item_id: str, media_type: MediaType) -> StreamDetails:
        """Get stream details (streaming URL and format) for given item."""
        stream_format = await self._get_stream_format(item_id=item_id)
        self.logger.debug(
            "Found stream_format: %s for song %s", stream_format["audio_ext"], item_id
        )

        extra_args = [
            "-user_agent",
            stream_format["user_agent"],
            "-referer",
            "https://www.nicovideo.jp/",
            "-headers",
            "Cookie: " + stream_format["cookies"] + "\r\n",
        ]

        stream_details = StreamDetails(
            provider=self.instance_id,
            item_id=item_id,
            audio_format=AudioFormat(
                content_type=ContentType.try_parse(stream_format["audio_ext"]),
            ),
            stream_type=StreamType.HTTP,
            path=stream_format["url"],
            extra_input_args=extra_args,
            allow_seek=True,
            can_seek=True,
            enable_cache=False,
        )

        if (
            stream_format.get("audio_channels")
            and str(stream_format.get("audio_channels")).isdigit()
        ):
            stream_details.audio_format.channels = int(stream_format.get("audio_channels") or 0)
        if stream_format.get("asr"):
            stream_details.audio_format.sample_rate = int(stream_format.get("asr") or 0)
        return stream_details

    async def resolve_image(self, path: str) -> str | bytes:
        """
        Resolve an image from an image path.

        This either returns (a generator to get) raw bytes of the image or
        a string with an http(s) URL or local path that is accessible from the server.
        """
        # This is an OPTIONAL method that you can implement to resolve image paths.
        # This is used to resolve image paths that are returned in the MediaItems.
        # You can return a URL to an image or a generator that yields the raw bytes of the image.
        # This will only be called when you set 'remotely_accessible'
        # to false in a MediaItemImage object.
        return path

    async def recommendations(self) -> list[RecommendationFolder]:
        """
        Get this provider's recommendations.

        Returns an actual (and often personalised) list of recommendations
        from this provider for the user/account.
        """
        # Get this provider's recommendations.
        # This is only called if you reported the RECOMMENDATIONS feature in the supported_features.
        return []

    async def _get_stream_format(self, item_id: str) -> dict[str, Any]:
        """Use yt-dlp to extract the best stream URL from Niconico."""
        netscape_cookie_str = convert_to_netscape(
            self.niconico_py_client.session.cookies, NICONICO_COOKIE_DOMAIN
        )

        def _extract() -> dict[str, Any]:
            url = f"https://www.nicovideo.jp/watch/{item_id}"
            ydl_opts = {
                "quiet": True,
                "format": "bestaudio/best",
                "nocheckcertificate": True,
                "noplaylist": True,
                "cookiefile": StringIO(netscape_cookie_str),
            }

            with YoutubeDL(ydl_opts) as ydl:
                try:
                    info = ydl.extract_info(url, download=False)
                    best_format = next(
                        (f for f in info["formats"] if f.get("acodec") != "none"), None
                    )
                    if not best_format:
                        raise UnplayableMediaError("No suitable audio stream found")
                    return {
                        "url": best_format["url"],
                        "audio_ext": best_format["ext"],
                        "audio_channels": best_format.get("channels"),
                        "asr": best_format.get("asr"),
                        "cookies": best_format["cookies"],
                        "user_agent": best_format["http_headers"].get("User-Agent", "Mozilla/5.0"),
                    }
                except Exception as err:
                    raise UnplayableMediaError(f"Niconico extract error: {err}") from err

        return await call_with_throttler(_extract)

    def is_logged_in(self) -> bool:
        """Check if the user is logged in to NicoNico."""
        return self.niconico_py_client.logined

    async def try_login(self) -> bool:
        """Attempt to login to NicoNico with the configured credentials."""
        if self.is_logged_in():
            return True

        username = self.config.get_value(CONF_USERNAME)
        password = self.config.get_value(CONF_PASSWORD)
        mfa = self.config.get_value(CONF_MFA)

        max_retries = 5
        retry_delay_seconds = 1

        async with niconico_api_throttler.bypass():
            for attempt in range(max_retries):
                try:
                    self.logger.info(
                        f"Trying to log in... (Number of attempts: {attempt + 1}/{max_retries})"
                    )
                    await asyncio.to_thread(
                        self.niconico_py_client.login_with_mail,
                        str(username),
                        str(password),
                        str(mfa) if mfa else None,
                    )
                    self.logger.info("Successful login!")
                    return True

                except LoginFailed as err:
                    self.logger.error("Login Failure: %s", err)
                    return False  # No retry and exit because of login information problem

                except (
                    Exception
                ) as e:  # Catch a wide range of exceptions and respond to network errors
                    if (
                        "Name or service not known" in str(e)
                        or "Max retries exceeded" in str(e)
                        or "ConnectionError" in str(e)
                    ):
                        self.logger.warning(
                            f"Network or DNS error occurred: {e}."
                            f" {retry_delay_seconds}秒後にリトライします..."
                        )
                        await asyncio.sleep(retry_delay_seconds)
                    else:
                        self.logger.error("An unexpected error has occurred.: %s", e)
                        return False

        self.logger.error(
            f"Could not login after exceeding the maximum number of retries ({max_retries})."
        )
        return False

    async def try_logout(self) -> None:
        """Log out from the NicoNico service."""
        if self.niconico_py_client:
            await call_with_throttler(
                self.niconico_py_client.get, "https://account.nicovideo.jp/logout"
            )
            self.niconico_py_client = NicoNico()


async def call_with_throttler(func: Callable[..., T], *args: Any, **kwargs: Any) -> T:
    """Ensure sequential execution of the function with delay between calls."""
    async with niconico_api_throttler.bypass():
        return await asyncio.to_thread(func, *args, **kwargs)


def _parse_playlist_by_mylist(
    provider: NiconicoMusicprovider, mylist: UserMylistItem | Mylist | EssentialMylist
) -> Playlist:
    """Parse a NicoNico UserMylistItem into a Playlist."""
    playlist = Playlist(
        item_id=str(mylist.id_),
        provider=provider.lookup_key,
        name=(mylist.title if isinstance(mylist, EssentialMylist) else mylist.name),
        owner=mylist.owner.id_ or "",
        metadata=MediaItemMetadata(),
        provider_mappings={
            ProviderMapping(
                item_id=str(mylist.id_),
                provider_domain=provider.domain,
                provider_instance=provider.instance_id,
                available=True,
            )
        },
    )

    if mylist.owner.icon_url:
        if not playlist.metadata.images:
            playlist.metadata.images = UniqueList()
        playlist.metadata.images.append(
            MediaItemImage(
                type=ImageType.THUMB,
                path=mylist.owner.icon_url,
                provider=provider.lookup_key,
                remotely_accessible=True,
            )
        )
    return playlist


def _parse_track_by_essential_video(
    provider: NiconicoMusicprovider, video: EssentialVideo
) -> Track:
    return Track(
        item_id=video.id_,
        provider=provider.lookup_key,
        name=video.title,
        duration=video.duration,
        artists=UniqueList([_parse_artist(provider, video.owner)]),
        metadata=MediaItemMetadata(
            images=UniqueList(
                [
                    MediaItemImage(
                        type=ImageType.THUMB,
                        path=video.thumbnail.nhd_url,
                        provider=provider.lookup_key,
                        remotely_accessible=True,
                    )
                ]
            )
        ),
        provider_mappings={
            ProviderMapping(
                item_id=video.id_,
                provider_domain=provider.domain,
                provider_instance=provider.instance_id,
                available=True,
            )
        },
    )


def _parse_artist(provider: NiconicoMusicprovider, owner_or_user: Owner | NicoUser) -> Artist:
    """Parse an Owner or NicoUser into an Artist."""
    item_id = str(owner_or_user.id_)
    name = str(owner_or_user.name if isinstance(owner_or_user, Owner) else owner_or_user.nickname)
    icon_url = (
        owner_or_user.icon_url if isinstance(owner_or_user, Owner) else owner_or_user.icons.large
    )
    artist = Artist(
        item_id=item_id,
        provider=provider.lookup_key,
        name=name,
        provider_mappings={
            ProviderMapping(
                item_id=item_id,
                provider_domain=provider.domain,
                provider_instance=provider.instance_id,
                available=True,
            )
        },
    )
    if icon_url:
        artist.metadata.add_image(
            MediaItemImage(
                type=ImageType.THUMB,
                path=icon_url,
                provider=provider.lookup_key,
            )
        )
    return artist


def convert_to_netscape(cookie: RequestsCookieJar, domain: str) -> str:
    """Convert a raw cookie into Netscape format for yt-dlp."""
    domain = domain.removeprefix("https://").removeprefix("http://")
    netscape_cookie = "# Netscape HTTP Cookie File\n"
    for morsel in iter(cookie):
        netscape_cookie += (
            f"{domain}\tTRUE\t/\t{str(morsel.secure).upper()}\t0\t{morsel.name}\t{morsel.value}\n"
        )
    return netscape_cookie
