"""
Inline single-page HTML for the Connect Wizard.

Embedded as a Python string (not a packaged static file) because
``pyproject.toml`` is auto-generated by ma-provider-tools and
``[tool.setuptools.package-data]`` cannot be hand-edited here without drift.
"""

from __future__ import annotations

HTML: str = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Connect Music Assistant — MCP Wizard</title>
<style>
  :root {
    --bg: #0f1218;
    --panel: #181c25;
    --border: #2a313e;
    --text: #e6e9ef;
    --muted: #9aa3b2;
    --accent: #5b8cff;
    --accent-strong: #7aa3ff;
    --good: #4ec07a;
    --bad: #ff6868;
    --code-bg: #0a0d12;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f7f8fb; --panel: #fff; --border: #e3e6ec;
      --text: #1a1d24; --muted: #5b6271;
      --accent: #2a5fdb; --accent-strong: #1f4cba;
      --code-bg: #f1f3f7;
    }
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    font-size: 14px; line-height: 1.5; }
  main { max-width: 980px; margin: 0 auto; padding: 24px 20px 64px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: var(--muted); margin-bottom: 24px; }
  .panel { background: var(--panel); border: 1px solid var(--border);
    border-radius: 10px; padding: 18px; margin-bottom: 16px; }
  .row { display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }
  label { font-weight: 500; color: var(--muted); margin-right: 6px; }
  input[type=text], input[type=password] {
    background: var(--code-bg); color: var(--text); border: 1px solid var(--border);
    border-radius: 6px; padding: 8px 10px; font-size: 14px; min-width: 220px;
    font-family: inherit; }
  button { background: var(--accent); color: #fff; border: 0; border-radius: 6px;
    padding: 8px 14px; font-size: 14px; cursor: pointer; font-weight: 500; }
  button:hover { background: var(--accent-strong); }
  button.secondary { background: transparent; color: var(--accent); border: 1px solid var(--border); }
  button.secondary:hover { border-color: var(--accent); background: rgba(91,140,255,0.08); }
  .url-toggle { display: inline-flex; gap: 4px; background: var(--code-bg);
    border: 1px solid var(--border); border-radius: 6px; padding: 2px; }
  .url-toggle button { background: transparent; color: var(--muted); padding: 4px 10px; font-size: 12px; }
  .url-toggle button.active { background: var(--accent); color: #fff; }
  pre.code { background: var(--code-bg); color: var(--text); padding: 14px;
    border-radius: 6px; border: 1px solid var(--border); overflow-x: auto;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px;
    white-space: pre; }
  .clients { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: 8px; margin: 12px 0; }
  .client-tab { background: var(--code-bg); border: 1px solid var(--border);
    color: var(--text); padding: 10px; border-radius: 6px; cursor: pointer;
    text-align: center; font-weight: 500; font-size: 13px; }
  .client-tab.active { background: var(--accent); border-color: var(--accent); color: #fff; }
  .client-tab:hover:not(.active) { border-color: var(--accent); }
  .methods { display: flex; gap: 8px; flex-wrap: wrap; margin: 12px 0 8px; }
  .method-tab { background: transparent; color: var(--text); border: 1px solid var(--border); }
  .method-tab.active { background: var(--accent); border-color: var(--accent); color: #fff; }
  .method-label.recommended::after { content: "Recommended"; margin-left: 7px;
    font-size: 10px; text-transform: uppercase; letter-spacing: .04em; opacity: .8; }
  .hint { color: var(--muted); font-size: 12px; margin: 6px 0; }
  .perm-list { display: flex; flex-wrap: wrap; gap: 6px; }
  .perm-pill { background: var(--code-bg); border: 1px solid var(--border);
    border-radius: 999px; padding: 3px 10px; font-size: 12px; color: var(--muted); }
  .perm-pill.on { color: var(--good); border-color: rgba(78,192,122,0.4); }
  .banner { padding: 10px 14px; border-radius: 6px; margin-bottom: 12px; }
  .banner.good { background: rgba(78,192,122,0.12); border: 1px solid rgba(78,192,122,0.4); color: var(--good); }
  .banner.bad { background: rgba(255,104,104,0.12); border: 1px solid rgba(255,104,104,0.4); color: var(--bad); }
  .small { font-size: 12px; color: var(--muted); }
  .actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 10px; }
  .hidden { display: none; }
  details { margin-top: 8px; }
  details summary { cursor: pointer; color: var(--accent); font-size: 13px; }
</style>
</head>
<body>
<main>
  <h1>Connect Music Assistant to your AI</h1>
  <div class="sub">Pick your AI client below and use the recommended connection method. A per-client
    token is minted in MA so you can revoke any one client without affecting the others.</div>

  <div id="msg"></div>
  <div id="loading" class="panel">Loading…</div>

  <section id="login-panel" class="panel hidden">
    <h2 style="margin-top:0;font-size:16px">Sign in to Music Assistant</h2>
    <div class="hint">Use your MA username and password.</div>
    <form id="login-form" class="row" style="margin-top:10px">
      <input type="text" name="username" placeholder="username" autocomplete="username" required>
      <input type="password" name="password" placeholder="password" autocomplete="current-password" required>
      <button type="submit">Sign in</button>
    </form>
  </section>

  <section id="wizard-panel" class="panel hidden">
    <div class="row" style="justify-content:space-between">
      <div>
        <label>MCP URL</label>
        <span id="url-display" class="small"></span>
      </div>
      <div class="url-toggle" id="url-toggle">
        <button data-which="network" class="active">Network</button>
        <button data-which="loopback">Loopback</button>
      </div>
    </div>

    <div class="hint" style="margin-top:12px">Pick your AI client:</div>
    <div id="clients" class="clients"></div>

    <div id="snippet-area" class="hidden">
      <div id="methods" class="methods hidden"></div>
      <div class="hint" id="path-hint"></div>
      <div id="generate-area">
        <button id="generate-btn">Generate connection details</button>
        <div class="hint" style="margin-top:6px">
          Mints a long-lived token labelled <code id="pending-token-name">MCP — …</code>.
        </div>
      </div>
      <div id="snippet-output" class="hidden">
        <pre id="snippet" class="code">…</pre>
        <div class="actions">
          <button id="copy-btn">Copy</button>
          <button id="download-btn" class="secondary">Download</button>
          <button id="share-btn" class="secondary">Share wizard URL</button>
          <button id="regen-btn" class="secondary">Re-generate</button>
        </div>
        <div id="notes-area" class="hint"></div>
        <div class="banner good" id="token-banner" style="margin-top:12px">
          Token shown once. Visible in MA → Profile → Long-lived access tokens as
          <code id="token-name">MCP — …</code>. Re-generating revokes any prior token for this client automatically.
        </div>
      </div>
    </div>
  </section>

  <section class="panel">
    <strong>Default policy</strong>
    <div id="perms" class="perm-list" style="margin-top:8px"></div>
    <details>
      <summary>What if my AI says "permission denied"?</summary>
      <div class="hint" style="margin-top:6px">
        Change the default profile in this plugin's settings. Token-specific
        overrides remain private to the settings screen and are not shown here.
      </div>
    </details>
  </section>

  <p class="small" style="text-align:center">
    <a href="https://github.com/trudenboy/ma-provider-mcp" style="color:var(--accent)">ma-provider-mcp</a>
    · Music Assistant MCP server
  </p>
</main>

<script>
(function() {
  "use strict";

  const SS = window.sessionStorage;
  const $ = (id) => document.getElementById(id);
  const state = {
    info: null,
    sessionToken: null,
    selectedClientId: null,
    selectedMethodIds: {},
    urlMode: "network",   // or "loopback"
    // Tokens belong to clients, not connection methods. Switching methods,
    // toggling URL mode, or re-clicking a client never mints another token.
    tokens: {},
    lastSnippet: "",
    lastFilename: "snippet.txt",
    setupCallback: null,
    setupCallbackSent: false,
  };
  try {
    const cachedTokens = JSON.parse(SS.getItem("ma_tokens") || "{}");
    if (cachedTokens && typeof cachedTokens === "object") state.tokens = cachedTokens;
  } catch (_) { /* ignore malformed cache */ }

  function showMsg(text, kind) {
    const el = $("msg");
    el.innerHTML = "";
    if (!text) return;
    const div = document.createElement("div");
    div.className = "banner " + (kind === "bad" ? "bad" : "good");
    div.textContent = text;
    el.appendChild(div);
  }

  async function fetchJSON(url, opts) {
    const res = await fetch(url, opts || {});
    let data = null;
    try { data = await res.json(); } catch (e) { /* may be empty */ }
    return { res: res, data: data };
  }

  function urlOf(mode) {
    if (!state.info) return "";
    return (mode === "network") ? state.info.mcp_url_advertised : state.info.mcp_url_loopback;
  }

  function renderClients() {
    const container = $("clients");
    container.innerHTML = "";
    state.info.clients.forEach((c) => {
      const tab = document.createElement("div");
      tab.className = "client-tab" + (c.id === state.selectedClientId ? " active" : "");
      tab.textContent = c.label;
      tab.dataset.id = c.id;
      tab.addEventListener("click", () => selectClient(c.id));
      container.appendChild(tab);
    });
  }

  function renderPerms() {
    const container = $("perms");
    container.innerHTML = "";
    const el = document.createElement("span");
    el.className = "perm-pill on";
    el.textContent = state.info.default_policy?.profile || "Safe queries";
    container.appendChild(el);
  }

  function findClient(id) {
    return state.info.clients.find((c) => c.id === id);
  }

  function selectedMethod(c) {
    if (!c || !c.methods || !c.methods.length) return null;
    const id = state.selectedMethodIds[c.id] || c.methods[0].id;
    return c.methods.find((method) => method.id === id) || c.methods[0];
  }

  function renderMethods(c) {
    const container = $("methods");
    container.innerHTML = "";
    container.classList.toggle("hidden", c.methods.length < 2);
    c.methods.forEach((method, index) => {
      const button = document.createElement("button");
      const active = method.id === selectedMethod(c).id;
      button.className = "method-tab" + (active ? " active" : "");
      const label = document.createElement("span");
      label.className = index === 0 ? "method-label recommended" : "method-label";
      label.textContent = method.label;
      button.appendChild(label);
      button.addEventListener("click", () => selectMethod(c.id, method.id));
      container.appendChild(button);
    });
  }

  function selectMethod(clientId, methodId) {
    state.selectedMethodIds[clientId] = methodId;
    renderSelected();
  }

  function selectClient(id) {
    state.selectedClientId = id;
    const c = findClient(id);
    if (c && !state.selectedMethodIds[id] && c.methods.length) {
      state.selectedMethodIds[id] = c.methods[0].id;
    }
    renderClients();
    renderSelected();
  }

  // Render the snippet area for the currently-selected client. Does NOT mint
  // a new token: if a token already exists in cache it re-renders from cache
  // (so URL-mode toggling and tab re-clicks are free); otherwise it shows a
  // "Generate config" call-to-action.
  function renderSelected() {
    const c = findClient(state.selectedClientId);
    if (!c) return;
    const method = selectedMethod(c);
    if (!method) return;
    const url = urlOf(state.urlMode);
    $("snippet-area").classList.remove("hidden");
    renderMethods(c);
    $("path-hint").textContent = method.config_path_hint || "";
    $("notes-area").textContent = method.notes || "";
    $("pending-token-name").textContent = "MCP — " + c.label;
    $("token-name").textContent = "MCP — " + c.label;
    $("url-display").textContent = url;
    const cachedToken = state.tokens[c.id];
    if (cachedToken) {
      const rendered = method.template.split("{{URL}}").join(url).split("{{TOKEN}}").join(cachedToken);
      state.lastSnippet = rendered;
      state.lastFilename = method.filename || (c.id + "-" + method.id + ".txt");
      $("snippet").textContent = rendered;
      $("snippet-output").classList.remove("hidden");
      $("generate-area").classList.add("hidden");
      $("copy-btn").classList.remove("hidden");
      $("download-btn").classList.toggle("hidden", method.action !== "download");
      signalSetupComplete();
    } else {
      $("snippet-output").classList.add("hidden");
      $("generate-area").classList.remove("hidden");
    }
  }

  // Mint a per-client long-lived token — only ever called from the explicit
  // "Generate config" / "Re-generate" button click handlers.
  async function mintForSelected() {
    const c = findClient(state.selectedClientId);
    if (!c) return;
    if (!state.sessionToken) {
      showMsg("Session expired — sign in again.", "bad");
      $("wizard-panel").classList.add("hidden");
      $("login-panel").classList.remove("hidden");
      return;
    }
    const { res, data } = await fetchJSON("./connect/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ session_token: state.sessionToken, client_id: c.id }),
    });
    if (res.status === 401) {
      SS.removeItem("ma_session_token");
      SS.removeItem("ma_tokens");
      state.sessionToken = null;
      state.tokens = {};
      showMsg("Session expired — sign in again.", "bad");
      $("wizard-panel").classList.add("hidden");
      $("login-panel").classList.remove("hidden");
      return;
    }
    if (!res.ok || !data || !data.token) {
      showMsg((data && data.error) || ("HTTP " + res.status), "bad");
      return;
    }
    state.tokens[c.id] = data.token;
    SS.setItem("ma_tokens", JSON.stringify(state.tokens));
    renderSelected();
    showMsg("Generated token for " + c.label + ".", "good");
    signalSetupComplete();
  }

  function parseSetupCallback(value) {
    if (!value || !value.startsWith("/")) return null;
    try {
      const callback = new URL(value, window.location.origin);
      if (callback.origin !== window.location.origin) return null;
      if (!/\\/setup_flow\\/callback\\/[a-f0-9]+$/.test(callback.pathname)) return null;
      return callback.pathname;
    } catch (_) {
      return null;
    }
  }

  async function signalSetupComplete() {
    if (!state.setupCallback || state.setupCallbackSent) return;
    state.setupCallbackSent = true;
    try {
      const response = await fetch(state.setupCallback, {
        method: "GET",
        credentials: "same-origin",
        cache: "no-store",
      });
      if (!response.ok) state.setupCallbackSent = false;
    } catch (_) {
      state.setupCallbackSent = false;
    }
  }

  function copyText(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text);
    }
    const ta = document.createElement("textarea");
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
    return Promise.resolve();
  }

  function setupHandlers() {
    $("url-toggle").querySelectorAll("button").forEach((b) => {
      b.addEventListener("click", () => {
        state.urlMode = b.dataset.which;
        $("url-toggle").querySelectorAll("button").forEach((x) =>
          x.classList.toggle("active", x.dataset.which === state.urlMode));
        // Re-render only — never mint another token just because the user
        // toggled the URL form. Snippet picks up the new URL from cache.
        if (state.selectedClientId) renderSelected();
      });
    });

    $("generate-btn").addEventListener("click", mintForSelected);
    $("regen-btn").addEventListener("click", () => {
      // Drop the cached token locally AND from sessionStorage immediately, so
      // a mint failure (network/5xx) plus a page reload cannot rehydrate the
      // stale token the user just asked to replace. Re-render right away so
      // the now-revoked token does not stay visible while the mint is in
      // flight. The server revokes the prior row by name (server-side
      // dedup), so no client-side prev_token_id plumbing is needed.
      const id = state.selectedClientId;
      if (id) {
        delete state.tokens[id];
        SS.setItem("ma_tokens", JSON.stringify(state.tokens));
        renderSelected();
      }
      mintForSelected();
    });

    $("copy-btn").addEventListener("click", () => {
      copyText(state.lastSnippet).then(() => showMsg("Copied snippet.", "good"));
    });

    $("download-btn").addEventListener("click", () => {
      const blob = new Blob([state.lastSnippet], { type: "text/plain" });
      const u = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = u; a.download = state.lastFilename;
      document.body.appendChild(a); a.click(); document.body.removeChild(a);
      URL.revokeObjectURL(u);
    });

    $("share-btn").addEventListener("click", () => {
      // Copy a clean wizard URL (no bootstrap query) so the user can open it
      // on a different device — useful for mobile QR-less hand-off.
      const wizardUrl = window.location.origin + window.location.pathname;
      copyText(wizardUrl).then(() => showMsg(
        "Wizard URL copied — open it on another device to generate configs there.", "good"));
    });

    $("login-form").addEventListener("submit", async (ev) => {
      ev.preventDefault();
      const fd = new FormData(ev.target);
      const username = fd.get("username");
      const password = fd.get("password");
      const { res, data } = await fetchJSON("./connect/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: username, password: password }),
      });
      if (!res.ok || !data || !data.session_token) {
        showMsg((data && data.error) || "Sign-in failed.", "bad");
        return;
      }
      state.sessionToken = data.session_token;
      SS.setItem("ma_session_token", state.sessionToken);
      $("login-panel").classList.add("hidden");
      // Render the client list + perms here too: init() only does so when the
      // user is already signed in at page-load (bootstrap fragment / cached
      // session). Without this, a fresh username/password sign-in revealed the
      // wizard panel with an empty "Pick your AI client" list.
      showWizard();
      showMsg("Signed in as " + (data.user && data.user.username || "user") + ".", "good");
    });
  }

  function showWizard() {
    // Reveal the wizard and populate it. Shared by init() (bootstrap/cached
    // session) and the login-form handler (interactive sign-in).
    $("wizard-panel").classList.remove("hidden");
    renderPerms();
    renderClients();
    // Preselect the first client so the user sees the path hint and the
    // "Generate config" CTA — but do NOT mint a token automatically; that
    // only happens on an explicit click.
    if (state.info.clients.length > 0) {
      selectClient(state.info.clients[0].id);
    }
  }

  async function tryBootstrap() {
    // Bootstrap arrives in the URL fragment (#bootstrap=…), not the query
    // string — fragments are never sent to the server (no access-log leak)
    // and not sent in cross-origin Referer (no leak to external links like
    // the GitHub footer link). The previous query-string form leaked both.
    const params = new URLSearchParams(window.location.hash.slice(1));
    state.setupCallback = parseSetupCallback(params.get("setup_callback"));
    const boot = params.get("bootstrap");
    history.replaceState({}, "", window.location.pathname);
    if (!boot) return false;
    const { res, data } = await fetchJSON("./connect/exchange", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ bootstrap: boot }),
    });
    if (!res.ok || !data || !data.session_token) return false;
    state.sessionToken = data.session_token;
    SS.setItem("ma_session_token", state.sessionToken);
    return true;
  }

  async function loadInfo() {
    const { res, data } = await fetchJSON("./connect/info");
    if (!res.ok || !data) {
      showMsg("Failed to load wizard info (HTTP " + res.status + ").", "bad");
      return false;
    }
    state.info = data;
    return true;
  }

  async function init() {
    setupHandlers();
    const okInfo = await loadInfo();
    if (!okInfo) {
      $("loading").textContent = "Failed to load.";
      return;
    }
    let signedIn = false;
    if (await tryBootstrap()) {
      signedIn = true;
    } else {
      const cached = SS.getItem("ma_session_token");
      if (cached) { state.sessionToken = cached; signedIn = true; }
    }

    $("loading").classList.add("hidden");

    if (signedIn) {
      showWizard();
    } else {
      renderPerms();
      $("login-panel").classList.remove("hidden");
    }
  }

  init();
})();
</script>
</body>
</html>
"""
