# ruff: noqa: D100, D101, D102

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

type RetVal = dict[str, Any] | None
type RetTuple = tuple[RetVal, RetVal]

SnapclientCallback = Callable[["SnapclientProto"], Any]
SnapgroupCallback = Callable[["SnapgroupProto"], Any]
SnapstreamCallback = Callable[["SnapstreamProto"], Any]


class SnapgroupProto(Protocol):
    @property
    def identifier(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def clients(self) -> list[str]: ...
    @property
    def stream(self) -> str: ...
    def callback(self) -> None: ...
    def set_callback(self, func: SnapgroupCallback | None) -> None: ...
    async def set_name(self, name: str) -> RetVal: ...
    async def set_stream(self, stream_id: str) -> RetVal: ...
    async def add_client(self, client_identifier: str) -> None: ...


class SnapclientProto(Protocol):
    # read-only properties used by your code
    @property
    def identifier(self) -> str: ...

    @property
    def group(self) -> SnapgroupProto | None: ...

    @property
    def friendly_name(self) -> str: ...

    @property
    def connected(self) -> bool: ...

    @property
    def name(self) -> str: ...

    @property
    def latency(self) -> int: ...

    @property
    def muted(self) -> bool: ...

    @property
    def volume(self) -> int: ...

    _client: dict[str, Any]

    def groups_available(self) -> list[SnapgroupProto]: ...

    async def set_muted(self, status: bool) -> None: ...
    async def set_volume(self, percent: int, update_group: bool = True) -> None: ...

    def callback(self) -> None: ...
    def set_callback(self, func: SnapclientCallback | None) -> None: ...


class SnapstreamProto(Protocol):
    _stream: dict[str, Any]

    @property
    def identifier(self) -> str: ...
    @property
    def friendly_name(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def path(self) -> str | None: ...
    def callback(self) -> None: ...
    def set_callback(self, func: SnapstreamCallback | None) -> None: ...


class SnapserverProto(Protocol):
    # lifecycle
    async def start(self) -> Any: ...
    def stop(self) -> None: ...

    # collections (as in the external lib: list(...) views)
    @property
    def groups(self) -> list[SnapgroupProto]: ...
    @property
    def clients(self) -> list[SnapclientProto]: ...
    @property
    def streams(self) -> list[SnapstreamProto]: ...

    # accessors
    def group(self, group_identifier: str) -> SnapgroupProto: ...
    def client(self, client_identifier: str) -> SnapclientProto: ...
    def stream(self, stream_identifier: str) -> SnapstreamProto: ...

    async def delete_client(self, identifier: str) -> RetTuple: ...

    async def status(self) -> tuple[Any, Any]: ...

    async def group_clients(self, identifier: str, clients: list[str]) -> RetVal: ...
    async def group_name(self, identifier: str, name: str) -> RetVal: ...
    async def group_stream(self, identifier: str, stream_id: str) -> RetVal: ...

    async def client_name(self, identifier: str, name: str) -> RetVal: ...
    async def client_latency(self, identifier: str, latency: int) -> RetVal: ...
    async def client_volume(self, identifier: str, volume: dict[str, Any]) -> RetVal: ...

    async def stream_add_stream(self, stream_uri: str) -> RetVal: ...
    async def stream_remove_stream(self, identifier: str) -> RetVal: ...

    # state sync
    def synchronize(self, status: dict[str, Any]) -> None: ...

    # callbacks (if you use them)
    def set_on_update_callback(self, func: Callable[[], Any] | None) -> None: ...
    def set_on_connect_callback(self, func: Callable[[], Any] | None) -> None: ...
    def set_on_disconnect_callback(self, func: Callable[[Exception], Any] | None) -> None: ...
    def set_new_client_callback(self, func: Callable[[SnapclientProto], Any] | None) -> None: ...
