const messages = {
    
    
    en: {
        // generic strings
        musicassistant: "Music Assistant",
        home: "Home",
        artists: "Artists",
        albums: "Albums",
        tracks: "Tracks",
        playlists: "Playlists",
        search: "Search",
        settings: "Settings",
        queue: "Queue",
        generic_settings: "Generic settings",
        music_providers: "Music providers",
        player_providers: "Player providers",
        player_settings: "Player settings",
        type_to_search: "Type here to search...",
        enabled: "Enabled",
        // settings strings
        username: "Username",
        password: "Password",
        hostname: "Hostname (or IP)",
        port: "Port",
        hass_url: "URL to homeassistant (e.g. https://homeassistant:8123)",
        hass_token: "Long Lived Access Token",
        hass_publish: "Publish players to Home Assistant",
        hass_player_power: "Attach player power to homeassistant entity",
        hass_player_source: "Source on the homeassistant entity (optional)",
        hass_player_volume: "Attach player volume to homeassistant entity",
        web_ssl_cert: "Path to ssl certificate file",
        web_ssl_key: "Path to ssl keyfile",
        web_ssl_host: "Hostname (FQDN used in the certificate)",
        player_enabled: "Enable player",
        player_name: "Custom name for this player",
        player_group_with: "Group this player to another (parent)player",
        player_mute_power: "Use muting as power control",
        player_disable_vol: "Disable volume controls",
        player_group_vol: "Apply group volume to childs (for group players only)",
        player_group_pow: "Apply group power based on childs (for group players only)",
        player_power_play: "Issue play command on power on",
        file_prov_music_path: "Path to music files",
        file_prov_playlists_path: "Path to playlists (.m3u)",
        // player strings
        players: "Players",
        play_on: "Play on:",
        play_now: "Play Now",
        play_next: "Play Next",
        add_queue: "Add to Queue",
        show_info: "Show info",
        state: {        
            playing: "playing",
            stopped: "stopped",
            paused: "paused",
            off: "off"
        }

    },

    nl: {
        // generic strings
        musicassistant: "Music Assistant",
        home: "Home",
        artists: "Artiesten",
        albums: "Albums",
        tracks: "Nummers",
        playlists: "Afspeellijsten",
        search: "Zoeken",
        settings: "Instellingen",
        queue: "Wachtrij",
        generic_settings: "Algemene instellingen",
        music_providers: "Muziek providers",
        player_providers: "Speler providers",
        player_settings: "Speler instellingen",
        enabled: "Ingeschakeld",
        type_to_search: "Type hier om te zoeken...",
        // settings strings
        username: "Gebruikersnaam",
        password: "Wachtwoord",
        hostname: "Hostnaam (of IP)",
        port: "Poort",
        hass_url: "URL naar homeassistant (b.v. https://homeassistant:8123)",
        hass_token: "Token met lange levensduur",
        hass_publish: "Publiceer spelers naar Home Assistant",
        hass_player_power: "Verbind speler aan/uit met homeassistant entity",
        hass_player_source: "Benodigde bron op de verbonden homeassistant entity (optioneel)",
        hass_player_volume: "Verbind volume van speler aan een homeassistant entity",
        web_ssl_cert: "Pad naar ssl certificaat bestand",
        web_ssl_key: "Pad naar ssl certificaat key bestand",
        web_ssl_host: "Hostname (FQDN van certificaat)",
        player_enabled: "Speler inschakelen",
        player_name: "Aangepaste naam voor deze speler",
        player_group_with: "Groupeer deze speler met een andere (hoofd)speler",
        player_mute_power: "Gebruik mute als aan/uit",
        player_disable_vol: "Schakel volume bediening helemaal uit",
        player_group_vol: "Pas groep volume toe op onderliggende spelers (alleen groep spelers)",
        player_group_pow: "Pas groep aan/uit toe op onderliggende spelers (alleen groep spelers)",
        player_power_play: "Automatisch afspelen bij inschakelen",
        file_prov_music_path: "Pad naar muziek bestanden",
        file_prov_playlists_path: "Pad naar playlist bestanden (.m3u)",
        // player strings
        players: "Spelers",
        play_on: "Afspelen op:",
        play_now: "Nu afspelen",
        play_next: "Speel als volgende af",
        add_queue: "Voeg toe aan wachtrij",
        show_info: "Bekijk informatie",
        state: {        
            playing: "afspelen",
            stopped: "gestopt",
            paused: "gepauzeerd",
            off: "uitgeschakeld"
        }
    }
}