"""Constants for the Pandora provider."""

from __future__ import annotations

# API Endpoints
API_BASE_URL = "https://www.pandora.com/api/v1"
LOGIN_ENDPOINT = f"{API_BASE_URL}/auth/login"
STATIONS_ENDPOINT = f"{API_BASE_URL}/station/getStations"
PLAYLIST_FRAGMENT_ENDPOINT = f"{API_BASE_URL}/playlist/getFragment"

# Error Codes from Pandora API
PANDORA_ERROR_CODES = {
    0: "INVALID_REQUEST",
    1: "INVALID_PARTNER",
    2: "LISTENER_NOT_AUTHORIZED",
    3: "USER_NOT_AUTHORIZED",
    4: "STATION_DOES_NOT_EXIST",
    5: "TRACK_NOT_FOUND",
    9: "PANDORA_NOT_AVAILABLE",
    10: "SYSTEM_NOT_AVAILABLE",
    11: "CALL_NOT_ALLOWED",
    12: "INVALID_USERNAME",
    13: "INVALID_PASSWORD",
    14: "DEVICE_NOT_FOUND",
    15: "PARTNER_NOT_AUTHORIZED",
    1000: "READ_ONLY_MODE",
    1001: "INVALID_AUTH_TOKEN",
    1002: "INVALID_LOGIN",
    1003: "LISTENER_NOT_AUTHORIZED",
    1004: "USER_ALREADY_EXISTS",
    1005: "DEVICE_ALREADY_ASSOCIATED_TO_ACCOUNT",
    1006: "UPGRADE_DEVICE_MODEL_INVALID",
    1009: "DEVICE_MODEL_INVALID",
    1010: "INVALID_SPONSOR",
    1018: "EXPLICIT_PIN_INCORRECT",
    1020: "EXPLICIT_PIN_MALFORMED",
    1023: "DEVICE_DISABLED",
    1024: "DAILY_TRIAL_LIMIT_REACHED",
    1025: "INVALID_SPONSOR_USERNAME",
    1026: "SPONSOR_CANNOT_SKIP_ADS",
    1027: "INSUFFICIENT_CONNECTIVITY",
    1034: "GEOLOCATION_REQUIRED",
}
