"""
Back-propagate dependency version bumps from ``requirements_all.txt`` into provider manifests.

``requirements_all.txt`` is autogenerated from ``pyproject.toml`` and every provider
``manifest.json`` (see ``gen_requirements_all``). Tools such as Dependabot only understand the
generated file and bump the pin there, which leaves the owning ``manifest.json`` — the real source
of truth — out of sync, so the next ``gen_requirements_all`` run reverts the bump and CI fails.

This script reads the (already edited) ``requirements_all.txt`` and rewrites the matching
requirement in every provider manifest that declares it, so a subsequent ``gen_requirements_all``
run is a no-op. Platform-conditional entries (the ``; sys_platform ...`` lines synthesised for
packages pinned to an alternate index, e.g. the PyTorch CPU wheels) are intentionally skipped:
those are never authored verbatim in a manifest.

When invoked with package-name arguments only those packages are reconciled (Dependabot's auto-fix
workflow passes the names it bumped, so the resulting commit stays scoped to that bump); with no
arguments every requirement in every manifest is reconciled against ``requirements_all.txt``.

Usage:
    python -m scripts.sync_manifest_from_requirements [PACKAGE ...]
"""

from __future__ import annotations

import json
import re
import sys
from collections.abc import Sequence
from pathlib import Path

# ruff: noqa: T201

REPO_ROOT = Path(__file__).resolve().parents[1]
PROVIDERS_PATH = REPO_ROOT / "music_assistant" / "providers"
REQUIREMENTS_FILE = REPO_ROOT / "requirements_all.txt"

# Leading distribution name of a requirement spec, e.g. "gql" from "gql[all]==4.0.0".
PACKAGE_NAME_REGEX = re.compile(r"^([A-Za-z0-9._-]+)")


def main(argv: Sequence[str] | None = None) -> int:
    """
    Rewrite provider manifest requirements to match ``requirements_all.txt``; print each change.

    :param argv: Package names to limit the reconciliation to; when omitted every requirement is
        reconciled.
    """
    raw_names = sys.argv[1:] if argv is None else argv
    only = {_normalize(name) for name in raw_names if name.strip()}
    wanted = _parse_requirements_all(REQUIREMENTS_FILE.read_text(encoding="utf-8"))
    if only:
        wanted = {name: spec for name, spec in wanted.items() if name in only}
    changes: list[str] = []
    for manifest_path in sorted(PROVIDERS_PATH.glob("*/manifest.json")):
        changes.extend(_sync_manifest(manifest_path, wanted))
    if changes:
        print("Updated provider manifest requirements:")
        for change in changes:
            print(f"  {change}")
    else:
        print("All provider manifests already in sync with requirements_all.txt")
    return 0


def _normalize(name: str) -> str:
    """Normalize a distribution name to its PEP 503 canonical form for matching."""
    return re.sub(r"[-_.]+", "-", name.strip()).lower()


def _package_name(spec: str) -> str | None:
    """Return the normalized distribution name of a requirement spec, or None for git/URL specs."""
    spec = spec.strip()
    if "://" in spec or spec.startswith("git+"):
        return None
    if match := PACKAGE_NAME_REGEX.match(spec):
        return _normalize(match.group(1))
    return None


def _parse_requirements_all(content: str) -> dict[str, str]:
    """
    Map each normalized package name in ``requirements_all.txt`` to its full requirement spec.

    :param content: The contents of ``requirements_all.txt``.
    """
    wanted: dict[str, str] = {}
    for raw_line in content.splitlines():
        line = raw_line.strip()
        # Skip the header comment, blank lines, index directives and the platform-conditional
        # entries gen_requirements_all synthesises for alternate-index packages (the PyTorch CPU
        # wheels), identified by their "platform_machine" marker. Those are never authored in a
        # manifest verbatim; any other PEP 508 environment marker is kept so it can still be synced.
        if not line or line.startswith(("#", "--")) or "platform_machine" in line:
            continue
        if (name := _package_name(line)) is not None:
            wanted[name] = line
    return wanted


def _sync_manifest(manifest_path: Path, wanted: dict[str, str]) -> list[str]:
    """
    Rewrite a single manifest's requirements in place to match ``wanted``; return the changes made.

    :param manifest_path: Path to the provider ``manifest.json``.
    :param wanted: Desired requirement spec per normalized package name.
    """
    text = manifest_path.read_text(encoding="utf-8")
    if manifest_path.is_relative_to(REPO_ROOT):
        rel = manifest_path.relative_to(REPO_ROOT).as_posix()
    else:
        rel = manifest_path.name
    requirements = json.loads(text).get("requirements", [])
    changes: list[str] = []
    for old_spec in requirements:
        name = _package_name(old_spec)
        if name is None or name not in wanted:
            continue
        new_spec = wanted[name]
        if new_spec != old_spec and f'"{old_spec}"' in text:
            text = text.replace(f'"{old_spec}"', f'"{new_spec}"')
            changes.append(f"{rel}: {old_spec} -> {new_spec}")
    if changes:
        manifest_path.write_text(text, encoding="utf-8", newline="\n")
    return changes


if __name__ == "__main__":
    sys.exit(main())
