#!/usr/bin/with-contenv bash
# ==============================================================================
# Run MusicAssistant
# ==============================================================================

# Enable Jemalloc
export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"

args="--config /data"

if [ "$DEBUG" = true ] ; then
    args="${args} --debug"
fi

exec python -m music_assistant ${args}