#!/usr/bin/with-contenv sh
# ==============================================================================
# Run MusicAssistant
# ==============================================================================

# Enable Jemalloc
export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"

args="--config /data"

if [ -z ${DEBUG} ]; then
    args="${args} --debug"
fi

exec python -m music_assistant ${args}