"""
PulseAudio card-profile selection for multi-channel cards.

A card's active profile decides which master sinks (and sources) exist at
all — if a surround-capable card comes up in a stereo profile, the
multi-channel master sink that remap_topology would build zones on simply
isn't there. Historically fixing this required host access (pavucontrol,
`ha audio`, or a hand-written custom.pa) — expert-level steps for someone
who just wants multiroom audio.

This module holds the pure decision logic (I/O — enumerate_pa_cards()
and set_card_profile() — lives in pa_simple, sharing its pactl/PULSE_SERVER
idiom). Profile selection becomes a local_audio concern:

  - resolve_profile() is a pure decision function: given a card snapshot
    and an optional user override, it returns what the active profile
    should be and why. The automatic policy is "most output channels,
    duplex-preferred": among output-capable profiles, pick the one whose
    name encodes the highest channel count, and among ties prefer a
    profile that also keeps an input side alive — so a companion capture
    provider (local_audio_in) on the same card is served by the same
    choice rather than fighting over it. Any provider running this same
    resolver converges on the same answer, which combined with
    set-only-if-different makes multiple writers naturally conflict-free.

  - plan_profile_changes() scopes the policy: only cards that local_audio
    is actually using (they back a currently-enumerated output sink) or
    that the user explicitly configured are ever considered. A bystander
    card — e.g. a capture-only USB mic used by some other addon — has no
    output sink, is never enumerated, and is therefore never touched.

Channel counts per profile are recovered from the profile *name*
(e.g. "output:analog-surround-71+input:analog-stereo" -> 8 output
channels, input present). PulseAudio's introspection metadata exposes
sink/source *counts* per profile but not channel counts, so the name is
the only structured source — and it is PA's own fixed mapping vocabulary
(analog-stereo, analog-surround-XY, hdmi-surroundXY, iec958-stereo, ...),
generated by PA itself, not vendor strings. This is the same reasoning
remap_topology.connector_label() already applies to sink names. Profiles
whose names don't parse (UCM "HiFi", "pro-audio", ...) are treated
conservatively: they are never switched *away from* while functional,
and never switched *to* automatically — only an explicit override
selects them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Final

# The reserved PulseAudio profile that disables a card entirely. Never a
# candidate for automatic selection.
PROFILE_OFF: Final = "off"

# Sentinel config value meaning "let the automatic policy decide".
PROFILE_AUTO: Final = "auto"

# PA mapping names that encode a fixed channel count without digits.
# "hdmi-surround" (5.1) predates "hdmi-surround71" in PA's vocabulary;
# "mono" and "stereo" cover analog-/iec958-/hdmi-/multichannel- prefixed
# stereo mappings via the substring checks in _mapping_channels().
_SURROUND_DIGITS_RE: Final = re.compile(r"surround-?(\d)(\d)")


def _mapping_channels(mapping: str) -> int | None:
    """
    Estimate the channel count encoded in one PA mapping name.

    :param mapping: A single mapping name from a profile-name part, e.g.
        "analog-surround-71", "hdmi-stereo-extra1", "iec958-stereo".
    :returns: Channel count, or None if the name doesn't follow PA's
        default profile-set vocabulary (UCM/pro-audio names).
    """
    if match := _SURROUND_DIGITS_RE.search(mapping):
        return int(match.group(1)) + int(match.group(2))
    if "surround" in mapping:
        # "hdmi-surround" without digits is PA's 5.1 HDMI mapping.
        return 6
    if "stereo" in mapping:
        return 2
    if "mono" in mapping:
        return 1
    return None


@dataclass(frozen=True, slots=True)
class ProfileCapability:
    """What a profile name says the profile offers."""

    output_channels: int | None
    """Highest channel count among the profile's output mappings, or None
    if the profile has no parseable output mapping."""

    has_output: bool
    """At least one "output:" part is present in the name."""

    has_input: bool
    """At least one "input:" part is present in the name."""


def parse_profile_name(profile_name: str) -> ProfileCapability:
    """
    Parse a PA card-profile name into its declared capability.

    Profile names are "+"-joined direction:mapping parts, e.g.
    "output:analog-surround-71+input:analog-stereo". A profile with
    multiple output parts (e.g. analog + iec958 simultaneously) is scored
    by its *largest* single output mapping — remap topology builds on one
    multi-channel master sink, so the widest sink is what matters.

    :param profile_name: The PA profile name (the machine name, not the
        human description).
    """
    output_channels: int | None = None
    has_output = False
    has_input = False
    for part in profile_name.split("+"):
        direction, _, mapping = part.partition(":")
        if direction == "output":
            has_output = True
            if (channels := _mapping_channels(mapping)) is not None:
                output_channels = max(output_channels or 0, channels)
        elif direction == "input":
            has_input = True
    return ProfileCapability(output_channels, has_output, has_input)


@dataclass(frozen=True, slots=True)
class CardProfile:
    """One profile a card offers (from PA card introspection)."""

    name: str
    description: str
    n_sinks: int
    n_sources: int
    priority: int
    available: bool


@dataclass(frozen=True, slots=True)
class CardSnapshot:
    """One card's introspection state at enumeration time."""

    name: str
    """PA card name, e.g. "alsa_card.pci-0000_05_00.0" — bus-path-derived
    and stable across reboots, same property class the sink-side hardware
    tag relies on."""

    index: int
    active_profile: str
    profiles: tuple[CardProfile, ...]
    alsa_card_name: str | None
    alsa_card_index: str | None
    """The "alsa.card" property (stringified index) — matches the
    "alsa_card_index" field on enumerate_pa_sinks() device dicts, which
    is how a card is linked to the output sinks local_audio is using."""


@dataclass(frozen=True, slots=True)
class ProfileDecision:
    """The resolver's verdict for one card."""

    card_name: str
    card_display_name: str
    current_profile: str
    target_profile: str | None
    """Profile to switch to, or None to leave the card untouched."""

    reason: str
    """Human-readable rationale, intended to be logged verbatim."""


def _profile_by_name(card: CardSnapshot, name: str) -> CardProfile | None:
    for profile in card.profiles:
        if profile.name == name:
            return profile
    return None


def _auto_candidates(card: CardSnapshot) -> list[tuple[int, bool, int, CardProfile]]:
    """
    Rank a card's automatically-selectable profiles.

    :returns: Sort keys and profiles, best first: (output channels,
        has-input, PA priority). Profiles with no sinks, unavailable
        profiles, "off", and unparsable names are excluded — an
        unparsable profile can't be ranked, so automatic selection never
        switches *to* it (an explicit override still can).
    """
    ranked: list[tuple[int, bool, int, CardProfile]] = []
    for profile in card.profiles:
        if profile.name == PROFILE_OFF or profile.n_sinks <= 0 or not profile.available:
            continue
        capability = parse_profile_name(profile.name)
        if capability.output_channels is None:
            continue
        has_input = capability.has_input or profile.n_sources > 0
        ranked.append((capability.output_channels, has_input, profile.priority, profile))
    ranked.sort(key=lambda item: (item[0], item[1], item[2]), reverse=True)
    return ranked


def resolve_profile(card: CardSnapshot, override: str | None = None) -> ProfileDecision:
    """
    Decide what one card's active profile should be.

    Pure function of the snapshot — no PA access, no side effects — so the
    policy is unit-testable and any caller (this provider, a capture-side
    provider) computes the same answer from the same card.

    :param card: The card's introspection snapshot.
    :param override: The user's configured profile name for this card, or
        None/PROFILE_AUTO for the automatic policy.
    :returns: A ProfileDecision; target_profile is None when the card
        should be left alone (already correct, nothing better offered, or
        not confidently rankable).
    """
    display = card.alsa_card_name or card.name
    active = _profile_by_name(card, card.active_profile)

    def keep(reason: str) -> ProfileDecision:
        return ProfileDecision(card.name, display, card.active_profile, None, reason)

    def switch(target: str, reason: str) -> ProfileDecision:
        return ProfileDecision(card.name, display, card.active_profile, target, reason)

    # --- Explicit override -------------------------------------------------
    if override and override != PROFILE_AUTO:
        if override == card.active_profile:
            return keep("configured profile already active")
        if _profile_by_name(card, override) is None:
            # e.g. the card's kernel driver changed the offered set, or the
            # config was copied between machines. Never guess a substitute
            # for an explicit user choice — leave the card alone and say so.
            return keep(f"configured profile '{override}' not offered by this card; leaving as-is")
        return switch(override, "user-configured profile")

    # --- Automatic: most output channels, duplex-preferred -----------------
    ranked = _auto_candidates(card)
    if not ranked:
        return keep("no rankable output profiles offered")
    best_channels, best_has_input, _, best = ranked[0]

    if best.name == card.active_profile:
        return keep("best-ranked profile already active")

    active_capability = parse_profile_name(card.active_profile) if active else None
    active_functional = active is not None and active.n_sinks > 0

    if not active_functional:
        # Input-only, "off", or a stale profile no longer offered: there is
        # no output sink to protect, so activating the best output profile
        # is a strict improvement.
        return switch(
            best.name,
            f"active profile has no output sinks; enabling {best_channels}ch output"
            + (" with input" if best_has_input else ""),
        )

    if active_capability is None or active_capability.output_channels is None:
        # Functional but unrankable (UCM "HiFi", pro-audio, ...): we cannot
        # show the switch is an upgrade, so never churn it automatically.
        return keep("active profile not rankable; leaving as-is (set an override to change it)")

    active_channels = active_capability.output_channels
    active_has_input = active_capability.has_input or (active is not None and active.n_sources > 0)

    if best_channels > active_channels:
        return switch(
            best.name,
            f"upgrading output {active_channels}ch -> {best_channels}ch"
            + (" (keeps input alive)" if best_has_input else ""),
        )
    if best_channels == active_channels and best_has_input and not active_has_input:
        return switch(
            best.name,
            f"same {best_channels}ch output, adding input side (duplex) for capture providers",
        )
    return keep("active profile already offers the widest output")


def cards_in_use(
    cards: list[CardSnapshot], devices: list[dict[str, Any]]
) -> list[CardSnapshot]:
    """
    Filter cards down to those backing a currently-enumerated output sink.

    This is the scoping rule that keeps the policy polite: local_audio
    only manages the profile of cards it is actually using. Matching is
    by the "alsa.card" index property (same value enumerate_pa_sinks()
    reports as alsa_card_index); alsa_card_name is a fallback used only
    for sinks whose proplist lacks the index, since names are shared by
    identical cards and by sibling functions of one chip.

    :param cards: All cards from enumerate_pa_cards().
    :param devices: Current enumerate_pa_sinks() result.
    """
    used_indexes = {
        str(d["alsa_card_index"]) for d in devices if d.get("alsa_card_index") is not None
    }
    # Name-based fallback ONLY for sinks whose proplist lacks the index
    # property. alsa_card_name is shared both by identical cards and by
    # sibling functions of the same chip (an "HD-Audio Generic" HDMI
    # function next to an "HD-Audio Generic" analog function), so a name
    # contributed by an index-bearing sink must not widen the match to
    # cards that sink already identified precisely — otherwise an unused
    # sibling card gets managed on the strength of its twin's sink.
    fallback_names = {
        d["alsa_card_name"]
        for d in devices
        if d.get("alsa_card_name") and d.get("alsa_card_index") is None
    }
    return [
        card
        for card in cards
        if (card.alsa_card_index is not None and card.alsa_card_index in used_indexes)
        or (card.alsa_card_name is not None and card.alsa_card_name in fallback_names)
    ]


def plan_profile_changes(
    cards: list[CardSnapshot],
    devices: list[dict[str, Any]],
    overrides: dict[str, str] | None = None,
) -> list[ProfileDecision]:
    """
    Produce profile decisions for every card local_audio should manage.

    Managed set = cards backing an enumerated output sink, plus any card
    with an explicit (non-auto) override — an override is the user
    directly pointing local_audio at a card, which counts as "in use"
    even if its current profile exposes no output sink yet (that is
    exactly the situation the override exists to fix).

    :param cards: All cards from enumerate_pa_cards().
    :param devices: Current enumerate_pa_sinks() result.
    :param overrides: Per-card configured profile, keyed by CardSnapshot
        name; missing/PROFILE_AUTO entries use the automatic policy.
    :returns: One ProfileDecision per managed card, in card order.
    """
    overrides = overrides or {}
    managed = {card.name: card for card in cards_in_use(cards, devices)}
    for card in cards:
        configured = overrides.get(card.name)
        if configured and configured != PROFILE_AUTO:
            managed.setdefault(card.name, card)
    return [
        resolve_profile(card, overrides.get(card.name)) for card in managed.values()
    ]

# ---------------------------------------------------------------------------
# Config-entry plumbing for the per-card override dropdowns.
# ---------------------------------------------------------------------------

# Prefix for per-card profile config-entry keys.
CONF_CARD_PROFILE_PREFIX: Final = "card_profile_"


def conf_card_profile_key(card_name: str) -> str:
    """
    Config-entry key for one card's profile override.

    Derived from the card's PA name (bus-path-based, stable across reboots
    and enumeration order — the same property class the sink-side hardware
    tag relies on), sanitized to a plain identifier so the key is safe in
    any config store. Two X-Fis differ by bus path, so their keys differ.

    :param card_name: CardSnapshot.name, e.g. "alsa_card.pci-0000_01_00.0".
    """
    return CONF_CARD_PROFILE_PREFIX + re.sub(r"[^A-Za-z0-9_]", "_", card_name)


def card_config_label(card: CardSnapshot) -> str:
    """
    Human label for one card's config entry.

    Combines the vendor card name with the bus-path suffix so identical
    cards are distinguishable ("Creative X-Fi (pci-0000_01_00.0)") and the
    label matches the card identifier the provider logs next to every
    profile decision.
    """
    bus_suffix = card.name.removeprefix("alsa_card.")
    if card.alsa_card_name:
        return f"{card.alsa_card_name} ({bus_suffix})"
    return bus_suffix
