"""
PulseAudio remap-sink topology computation for multi-channel cards.

For any output sink with more than 2 channels, computes the set of
module-remap-sink.c sinks local_audio should create:
  - one stereo "zone" sink per recognized channel pair present in the
    master's channel map (front/rear/side stereo, center+sub), always
    exposed to clients as front-left,front-right regardless of which
    physical channels they pull from, and
  - one full-passthrough sink (same channel count and channel map as the
    master) for sinks with 6+ channels, giving "play to all outputs"
    behavior with independent hardware volume control.

This mirrors the channel-pair definitions and naming convention previously
implemented by an external PulseAudio stereo-pairs addon, so that existing
sink names/layouts are preserved when local_audio takes over creating them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Final

# Recognized stereo zone pairs: suffix -> (master channel 1, master channel 2).
# A zone is created only if BOTH channels are present in the master's
# channel map. The zone sink always exposes front-left,front-right to
# clients regardless of which physical channels it pulls from.
STEREO_PAIRS: Final[dict[str, tuple[str, str]]] = {
    "front_stereo": ("front-left", "front-right"),
    "rear_stereo": ("rear-left", "rear-right"),
    "side_stereo": ("side-left", "side-right"),
    "center_sub": ("front-center", "lfe"),
}

# Minimum master channel count for a full-passthrough "multichannel stereo"
# sink (named after the AVR "Multi Channel Stereo" / "All Channel Stereo"
# mode — plays the same content to all output pairs).
SURROUND_PASSTHROUGH_MIN_CHANNELS: Final = 6

ZONE_CHANNEL_MAP: Final[tuple[str, str]] = ("front-left", "front-right")


@dataclass(frozen=True, slots=True)
class RemapSinkSpec:
    """A single module-remap-sink.c sink to create."""

    sink_name: str
    description: str
    master_channel_map: tuple[str, ...]
    channel_map: tuple[str, ...]
    channels: int


def normalize_card_name(
    alsa_card_name: str, hardware_tag: str | None = None, label: str | None = None
) -> str:
    """
    Normalize an alsa.card_name property into a sink-name prefix.

    Mirrors `tr ' -' '_' | tr -cd '[:alnum:]_'`, e.g. "Creative X-Fi" ->
    "Creative_X_Fi", "HD-Audio Generic" -> "HD_Audio_Generic".

    :param hardware_tag: Optional short stable hash tag (see
        sendspin_bridge.short_hardware_tag(), derived from the master
        sink's own PA name — bus-path-derived, so it stays the same
        across reboots regardless of ALSA card-index enumeration order,
        unlike the ALSA card index itself). Appended to disambiguate
        identical cards (e.g. two X-Fi cards become
        ``Creative_X_Fi_a3f9`` and ``Creative_X_Fi_7c21``). Applied
        unconditionally, not just on detected collision, so a card's
        sink-name prefix never changes later purely because a second
        identical card was added — see short_hardware_tag()'s docstring
        for the same rationale applied to player display names.
    :param label: Optional connector-type label (see connector_label()),
        e.g. "hdmi", inserted before the hardware-tag suffix so an HDMI
        output and an analog output sharing an identical alsa.card_name
        (two functions on the same physical chip, e.g. "HD-Audio Generic")
        are distinguishable at a glance rather than differing only by an
        opaque tag: "HD_Audio_Generic_hdmi_a3f9" vs
        "HD_Audio_Generic_7c21".
    """
    name = re.sub(r"[ -]", "_", alsa_card_name)
    name = re.sub(r"[^A-Za-z0-9_]", "", name)
    if label:
        name = f"{name}_{label}"
    if hardware_tag:
        name = f"{name}_{hardware_tag}"
    return name


def connector_label(device_bus: str | None, master_sink_name: str) -> str | None:
    """
    Derive a short connector-type label for disambiguating card names.

    Distinguishes an HDMI output from an analog output on the same chip
    (which can share an identical alsa.card_name), and more generally
    labels a card's connection type without relying on vendor-supplied
    naming — some USB DACs (e.g. certain class-compliant devices) don't
    self-identify as USB anywhere in their alsa.card_name/product string.

    :param device_bus: The "device.bus" PA property ("pci", "usb", ...) —
        structured connection-type data from PulseAudio's own kernel-bus
        detection, not vendor naming.
    :param master_sink_name: The master sink's own PA sink name. HDMI is
        detected via "hdmi" in *this* name specifically because it comes
        from PulseAudio's own ACP profile-naming convention (e.g.
        "alsa_output.pci-...hdmi-surround-extra1"), generated by PA itself
        — a fixed, reliable vocabulary, unlike vendor product strings.
    :returns: "hdmi", "spdif" (for a plain PCM S/PDIF/IEC958 output — not to
        be confused with compressed bitstream passthrough, which is a
        separate, unrelated code path entirely), "analog" (for any other
        PCI device), the lowercased device_bus value for anything else
        (e.g. "usb"), or None if no signal is available at all.
    """
    name_lower = master_sink_name.lower()
    if "hdmi" in name_lower:
        return "hdmi"
    if "iec958" in name_lower or "spdif" in name_lower:
        return "spdif"
    if device_bus == "pci":
        return "analog"
    if device_bus:
        return device_bus.lower()
    return None


def compute_remap_topology(
    card_name: str,
    channel_map: list[str],
    max_output_channels: int,
    display_prefix: str | None = None,
    hardware_tag: str | None = None,
) -> list[RemapSinkSpec]:
    """
    Compute the remap-sink topology for one multi-channel master sink.

    :param card_name: Normalized card name prefix, including the hardware
        tag (see normalize_card_name), used as f"{card_name}_{suffix}" for
        each sink's actual PA sink_name — this must stay tag-included so
        two identical cards' sinks never collide.
    :param channel_map: The master sink's PA channel map (channel position
        names, e.g. ["front-left", "front-right", "rear-left", ...]).
    :param max_output_channels: The master sink's channel count.
    :param display_prefix: Optional untagged card name prefix (i.e.
        normalize_card_name() called without a hardware_tag), used as the
        base of each sink's PA "description" property. Falls back to
        card_name (tag included) if not given.
    :param hardware_tag: Optional short stable hash tag (see
        sendspin_bridge.short_hardware_tag()), embedded into each sink's
        description as "..._[tag]_suffix" — positioned before the zone
        suffix rather than at the very end, so that sorting players by
        name groups every zone of the same physical card together (with
        zone type as the secondary sort key within that group), rather
        than grouping same-named zones together across different cards.
    :returns: List of RemapSinkSpec to create. Empty if the master is
        already stereo or smaller (channels <= 2) — nothing to remap.
    """
    if max_output_channels <= 2:
        return []

    description_prefix = display_prefix if display_prefix is not None else card_name
    tag_infix = f"_[{hardware_tag}]" if hardware_tag else ""
    channel_set = set(channel_map)
    specs: list[RemapSinkSpec] = []

    for suffix, (ch_a, ch_b) in STEREO_PAIRS.items():
        if ch_a in channel_set and ch_b in channel_set:
            specs.append(
                RemapSinkSpec(
                    sink_name=f"{card_name}_{suffix}",
                    description=f"{description_prefix}{tag_infix}_{suffix}",
                    master_channel_map=(ch_a, ch_b),
                    channel_map=ZONE_CHANNEL_MAP,
                    channels=2,
                )
            )

    if max_output_channels >= SURROUND_PASSTHROUGH_MIN_CHANNELS:
        specs.append(
            RemapSinkSpec(
                sink_name=f"{card_name}_multichannel_stereo",
                description=f"{description_prefix}{tag_infix}_multichannel_stereo",
                master_channel_map=tuple(channel_map),
                channel_map=tuple(channel_map),
                channels=max_output_channels,
            )
        )

    return specs


def build_remap_sink_argument(spec: RemapSinkSpec, master_sink_name: str) -> str:
    """Build the module-remap-sink.c argument string for a RemapSinkSpec."""
    return (
        f"sink_name={spec.sink_name} "
        f"master={master_sink_name} "
        f"sink_properties=device.description={spec.description} "
        f"channels={spec.channels} "
        f"master_channel_map={','.join(spec.master_channel_map)} "
        f"channel_map={','.join(spec.channel_map)} "
        f"remix=no"
    )


# Canonical set of remap-sink suffixes this module ever creates. Used to
# recover which zone a given remap sink represents purely from its own PA
# sink name — reliable because these are literal strings we control and
# construct sink names from ("{card_name}_{suffix}"), not inferred from
# anything vendor- or driver-supplied.
KNOWN_REMAP_SUFFIXES: Final[tuple[str, ...]] = (*STEREO_PAIRS.keys(), "multichannel_stereo")


def remap_zone_suffix(sink_name: str) -> str | None:
    """
    Recover which zone a remap sink represents from its own PA sink name.

    :param sink_name: A remap sink's own PA sink name (e.g.
        "HD_Audio_Generic_hdmi_card2_multichannel_stereo").
    :returns: The matching suffix (e.g. "multichannel_stereo"), or None if
        sink_name doesn't end with any known suffix — e.g. it isn't a
        remap sink this module created.
    """
    for suffix in KNOWN_REMAP_SUFFIXES:
        if sink_name.endswith(f"_{suffix}"):
            return suffix
    return None
