"""Tests for scoping pip-audit findings to the vulnerabilities a pull request introduces."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.audit_changed_packages import (
    audit_status,
    changed_packages,
    introduced_packages,
    main,
    normalize,
    requirement_versions,
    vulnerable_packages,
)

# Resolved dependency set of the target branch, as the audit workflow writes it
BASE_CLOSURE = """
aiohttp==3.14.1
clean-package==1.0.0
"""


def audit_report(*vulnerable: str, skipped: str | None = None) -> str:
    """
    Return a pip-audit JSON report where the given packages carry a vulnerability.

    :param vulnerable: Packages to report a vulnerability for, as `name` or `name==version`.
    :param skipped: Package name pip-audit could not audit, if any.
    """
    dependencies = []
    for entry in vulnerable:
        name, _, version = entry.partition("==")
        dependencies.append(
            {
                "name": name,
                "version": version or "1.0.0",
                "vulns": [{"id": "GHSA-test", "fix_versions": []}],
            }
        )
    dependencies.append({"name": "clean-package", "version": "1.0.0", "vulns": []})
    if skipped:
        dependencies.append({"name": skipped, "skip_reason": "not found on PyPI"})
    return json.dumps({"dependencies": dependencies, "fixes": []})


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("aiohttp", "aiohttp"),
        ("Zeroconf", "zeroconf"),
        ("aiohttp_fast_zlib", "aiohttp-fast-zlib"),
        ("zope.interface", "zope-interface"),
        ("a__b", "a-b"),
    ],
)
def test_normalize(name: str, expected: str) -> None:
    """Package names are compared in their PEP 503 normalized form."""
    assert normalize(name) == expected


def test_changed_packages_reads_requirement_lines() -> None:
    """Package names are extracted regardless of the version specifier used."""
    requirements = """
        aiohttp==3.14.1
        music-assistant-models>=1.2
        some_pkg[extra]~=2.0 ; python_version >= '3.14'
        aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1

        # a comment
        --index-url https://example.org/simple
    """
    assert changed_packages(requirements) == {
        "aiohttp",
        "music-assistant-models",
        "some-pkg",
        "aiolibdatachannel",
    }


def test_requirement_versions_reads_pinned_versions() -> None:
    """A resolved dependency set pins one version per package, except for URL requirements."""
    closure = """
        # This file was autogenerated by uv
        --extra-index-url https://example.org/simple
        aiohttp==3.14.1
        some_pkg[extra]==2.0
        torch==2.13.0+cpu ; sys_platform == 'linux'
        aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1
    """
    assert requirement_versions(closure) == {
        "aiohttp": {"3.14.1"},
        "some-pkg": {"2.0"},
        "torch": {"2.13.0+cpu"},
        "aiolibdatachannel": set(),
    }


def test_vulnerable_packages_ignores_clean_and_skipped() -> None:
    """Only packages with findings count; skipped ones carry no vulns key."""
    report = audit_report("aiohttp==3.14.3", skipped="torch")
    assert vulnerable_packages(report) == {("aiohttp", "3.14.3")}


def test_introduced_packages_compares_name_and_version() -> None:
    """A finding is introduced unless the target branch resolves to that exact version."""
    resolved = {"aiohttp": {"3.14.1"}, "aiolibdatachannel": set()}
    findings = {
        ("aiohttp", "3.14.1"),
        ("aiohttp", "3.14.3"),
        ("transformers", "5.14.1"),
        ("aiolibdatachannel", "0.1.0"),
    }
    assert introduced_packages(findings, resolved) == {
        ("aiohttp", "3.14.3"),
        ("transformers", "5.14.1"),
    }


def test_no_findings_passes() -> None:
    """A clean audit passes even when the pull request changes dependencies."""
    assert audit_status(audit_report(), "aiohttp==3.14.1", BASE_CLOSURE) == "pass"


def test_findings_the_target_branch_has_too_are_preexisting() -> None:
    """Vulnerabilities the target branch already installs describe it, not the pull request."""
    assert audit_status(audit_report("aiohttp==3.14.1"), "aiohttp==3.14.1", BASE_CLOSURE) == (
        "preexisting"
    )


def test_findings_in_a_bumped_package_fail() -> None:
    """A version the target branch does not install is one this pull request brings in."""
    assert audit_status(audit_report("aiohttp==3.14.3"), "aiohttp==3.14.3", BASE_CLOSURE) == "fail"


def test_findings_in_a_new_transitive_package_fail() -> None:
    """A vulnerability pulled in indirectly gates too, even with no direct requirement for it."""
    assert audit_status(audit_report("transformers==5.14.1"), "beat-this==1.1.0", BASE_CLOSURE) == (
        "fail"
    )


def test_an_unreadable_target_branch_set_raises() -> None:
    """A resolved set no package can be read from must fail loudly rather than gate everything."""
    with pytest.raises(ValueError, match="No packages"):
        audit_status(audit_report("aiohttp"), "", '{"packages": [{"name": "aiohttp"}]}')


def test_findings_without_a_target_branch_set_compare_changed_requirements() -> None:
    """Resolving the target branch can fail; the changed requirements remain a usable basis."""
    assert audit_status(audit_report("aiohttp"), "some-pkg==1.0") == "preexisting"
    assert audit_status(audit_report("aiohttp"), "aiohttp==3.14.1") == "fail"


def test_findings_without_dependency_changes_are_preexisting() -> None:
    """A pull request that changes no dependency can never introduce a vulnerability."""
    assert audit_status(audit_report("aiohttp"), "") == "preexisting"


def test_findings_match_across_name_spellings() -> None:
    """The comparison survives the underscore/dash spellings both sides use."""
    assert audit_status(audit_report("aiohttp_fast_zlib"), "aiohttp-fast-zlib==0.3.0") == "fail"


def test_main_prints_status(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """The status is printed for the reporting workflow to pick up."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp==3.14.3"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("aiohttp==3.14.3\n")
    base_closure = tmp_path / "base_closure.txt"
    base_closure.write_text(BASE_CLOSURE)

    assert main([str(audit), str(requirements), str(base_closure)]) == 0
    assert capsys.readouterr().out.strip() == "fail"


def test_main_without_a_base_closure_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The resolved set is absent when the target branch could not be resolved."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("transformers==5.14.1"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("beat-this==1.1.0\n")

    assert main([str(audit), str(requirements), str(tmp_path / "missing.txt")]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


def test_main_without_a_requirements_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The requirements file is absent when the analysis found no dependency changes."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp"))

    assert main([str(audit), str(tmp_path / "missing.txt")]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


@pytest.mark.parametrize(
    ("report", "expected"),
    [
        ("not json at all", json.JSONDecodeError),
        # A pip-audit release that renames the key must not read as "no findings"
        ('{"deps": [], "fixes": []}', KeyError),
    ],
)
def test_an_unusable_report_raises(tmp_path: Path, report: str, expected: type[Exception]) -> None:
    """An unreadable audit must fail loudly; the workflow gates on a non-zero exit."""
    audit = tmp_path / "audit.json"
    audit.write_text(report)

    with pytest.raises(expected):
        main([str(audit), str(tmp_path / "missing.txt")])


def test_a_missing_report_raises(tmp_path: Path) -> None:
    """pip-audit writing no report at all must fail loudly rather than pass."""
    with pytest.raises(FileNotFoundError):
        main([str(tmp_path / "missing.json"), str(tmp_path / "missing.txt")])
