"""Tests for scoping pip-audit findings to the vulnerabilities a pull request introduces."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.audit_changed_packages import (
    audit_status,
    changed_packages,
    introduced_packages,
    main,
    normalize,
    requirement_versions,
    resolved_findings,
    vulnerable_packages,
)

# Resolved dependency set of the target branch, as the audit workflow writes it
BASE_CLOSURE = """
aiohttp==3.14.1
clean-package==1.0.0
"""


def audit_report(*vulnerable: str, skipped: str | None = None) -> str:
    """
    Return a pip-audit JSON report where the given packages carry a vulnerability.

    :param vulnerable: Packages to report a vulnerability for, as `name` or `name==version`.
    :param skipped: Package name pip-audit could not audit, if any.
    """
    dependencies = []
    for entry in vulnerable:
        name, _, version = entry.partition("==")
        dependencies.append(
            {
                "name": name,
                "version": version or "1.0.0",
                "vulns": [{"id": "GHSA-test", "fix_versions": []}],
            }
        )
    dependencies.append({"name": "clean-package", "version": "1.0.0", "vulns": []})
    if skipped:
        dependencies.append({"name": skipped, "skip_reason": "not found on PyPI"})
    return json.dumps({"dependencies": dependencies, "fixes": []})


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("aiohttp", "aiohttp"),
        ("Zeroconf", "zeroconf"),
        ("aiohttp_fast_zlib", "aiohttp-fast-zlib"),
        ("zope.interface", "zope-interface"),
        ("a__b", "a-b"),
    ],
)
def test_normalize(name: str, expected: str) -> None:
    """Package names are compared in their PEP 503 normalized form."""
    assert normalize(name) == expected


def test_changed_packages_reads_requirement_lines() -> None:
    """Package names are extracted regardless of the version specifier used."""
    requirements = """
        aiohttp==3.14.1
        music-assistant-models>=1.2
        some_pkg[extra]~=2.0 ; python_version >= '3.14'
        aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1

        # a comment
        --index-url https://example.org/simple
    """
    assert changed_packages(requirements) == {
        "aiohttp",
        "music-assistant-models",
        "some-pkg",
        "aiolibdatachannel",
    }


def test_requirement_versions_reads_pinned_versions() -> None:
    """A resolved dependency set pins one version per package, except for URL requirements."""
    closure = """
        # This file was autogenerated by uv
        --extra-index-url https://example.org/simple
        aiohttp==3.14.1
        some_pkg[extra]==2.0
        torch==2.13.0+cpu ; sys_platform == 'linux'
        aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1
    """
    assert requirement_versions(closure) == {
        "aiohttp": {"3.14.1"},
        "some-pkg": {"2.0"},
        "torch": {"2.13.0+cpu"},
        "aiolibdatachannel": set(),
    }


def test_requirement_versions_collects_every_pinned_version() -> None:
    """A package can appear more than once, as the marker-split torch requirements do."""
    closure = """
        torch==2.13.0+cpu ; sys_platform == 'linux' and platform_machine == 'x86_64'
        torch==2.13.0 ; sys_platform != 'linux' or platform_machine != 'x86_64'
    """
    assert requirement_versions(closure) == {"torch": {"2.13.0+cpu", "2.13.0"}}


def test_vulnerable_packages_ignores_clean_and_skipped() -> None:
    """Only packages with findings count; skipped ones carry no vulns key."""
    report = audit_report("aiohttp==3.14.3", skipped="torch")
    assert vulnerable_packages(report) == {("aiohttp", "3.14.3")}


def test_introduced_packages_compares_name_and_version() -> None:
    """A finding is introduced unless the target branch resolves to that exact version."""
    resolved = {"aiohttp": {"3.14.1"}, "aiolibdatachannel": set()}
    findings = {
        ("aiohttp", "3.14.1"),
        ("aiohttp", "3.14.3"),
        ("transformers", "5.14.1"),
        ("aiolibdatachannel", "0.1.0"),
    }
    assert introduced_packages(findings, resolved) == {
        ("aiohttp", "3.14.3"),
        ("transformers", "5.14.1"),
    }


def test_introduced_packages_reads_a_url_pin_from_the_changed_requirements() -> None:
    """A package the target branch pins by URL is only introduced when its requirement changes."""
    findings = {("aiolibdatachannel", "0.1.0")}
    resolved: dict[str, set[str]] = {"aiolibdatachannel": set()}

    assert introduced_packages(findings, resolved) == set()
    assert introduced_packages(findings, resolved, {"aiolibdatachannel"}) == findings


def test_resolved_findings_keeps_what_the_set_installs() -> None:
    """Only findings the resolved set carries count; a URL requirement matches on name alone."""
    resolved = {"aiohttp": {"3.14.1"}, "aiolibdatachannel": set()}
    findings = {
        ("aiohttp", "3.14.1"),
        ("aiohttp", "3.14.3"),
        ("transformers", "5.14.1"),
        ("aiolibdatachannel", "0.1.0"),
    }
    assert resolved_findings(findings, resolved) == {
        ("aiohttp", "3.14.1"),
        ("aiolibdatachannel", "0.1.0"),
    }


def test_no_findings_passes() -> None:
    """A clean audit passes even when the pull request changes dependencies."""
    assert audit_status(audit_report(), "aiohttp==3.14.1", BASE_CLOSURE) == "pass"


def test_findings_the_target_branch_has_too_are_preexisting() -> None:
    """Vulnerabilities the target branch already installs describe it, not the pull request."""
    report = audit_report("aiohttp==3.14.1")

    assert audit_status(report, "aiohttp==3.14.1", BASE_CLOSURE) == "preexisting"
    assert audit_status(report, "aiohttp==3.14.1", BASE_CLOSURE, BASE_CLOSURE) == "preexisting"


def test_findings_in_a_bumped_package_fail() -> None:
    """A version the target branch does not install is one this pull request brings in."""
    assert audit_status(audit_report("aiohttp==3.14.3"), "aiohttp==3.14.3", BASE_CLOSURE) == "fail"


def test_findings_in_a_new_transitive_package_fail() -> None:
    """A vulnerability pulled in indirectly gates too, even with no direct requirement for it."""
    assert audit_status(audit_report("transformers==5.14.1"), "beat-this==1.1.0", BASE_CLOSURE) == (
        "fail"
    )


def test_a_release_published_during_the_run_is_not_gated() -> None:
    """The environment is installed before either branch is resolved; that skew must not gate."""
    # Both branches resolve to the release that landed after the environment was installed
    closure = "aiohttp==3.14.3\nclean-package==1.0.0\n"
    report = audit_report("aiohttp==3.14.1")
    changed = "music-assistant-models==1.1.183"

    assert audit_status(report, changed, closure) == "fail"
    assert audit_status(report, changed, closure, closure) == "preexisting"


def test_findings_not_gated_on_are_named(capsys: pytest.CaptureFixture[str]) -> None:
    """What the pull request's resolution carries instead tells an artifact from a mistake."""
    closure = "aiohttp==3.14.3\nclean-package==1.0.0\n"
    report = audit_report("aiohttp==3.14.1", "transformers==5.14.1")

    assert audit_status(report, "music-assistant-models==1.1.183", closure, closure) == (
        "preexisting"
    )
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "`aiohttp 3.14.1` (resolved to 3.14.3)" in captured.err
    assert "`transformers 5.14.1` (not in the resolved set)" in captured.err


def test_gated_findings_are_not_named(capsys: pytest.CaptureFixture[str]) -> None:
    """Nothing is set aside when the pull request's own resolution carries every finding."""
    head_closure = "aiohttp==3.14.3\nclean-package==1.0.0\n"

    assert audit_status(audit_report("aiohttp==3.14.3"), "", BASE_CLOSURE, head_closure) == "fail"
    assert capsys.readouterr().err == ""


def test_findings_the_pull_request_resolves_to_still_fail() -> None:
    """A bumped version the pull request's own resolution carries is genuinely introduced."""
    head_closure = "aiohttp==3.14.3\nclean-package==1.0.0\n"
    report = audit_report("aiohttp==3.14.3")

    assert audit_status(report, "aiohttp==3.14.3", BASE_CLOSURE, head_closure) == "fail"


def test_swapping_a_url_pin_for_a_vulnerable_release_fails() -> None:
    """Replacing a URL requirement with a published version brings that version in."""
    base_closure = "aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1"
    report = audit_report("aiolibdatachannel==0.1.0")

    assert audit_status(report, "aiolibdatachannel==0.1.0", base_closure) == "fail"
    assert audit_status(report, "", base_closure) == "preexisting"


def test_a_changed_url_pin_fails_against_both_resolutions() -> None:
    """A URL requirement pins no version, so the pull request's resolution matches on name."""
    base_closure = "aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v1"
    head_closure = "aiolibdatachannel @ git+https://github.com/example/aiolibdatachannel@v2"
    report = audit_report("aiolibdatachannel==0.1.0")

    assert audit_status(report, head_closure, base_closure, head_closure) == "fail"


def test_an_unreadable_target_branch_set_raises() -> None:
    """A resolved set no package can be read from must fail loudly rather than gate everything."""
    with pytest.raises(ValueError, match="No packages"):
        audit_status(audit_report("aiohttp"), "", '{"packages": [{"name": "aiohttp"}]}')


def test_an_unreadable_pull_request_set_raises() -> None:
    """The same holds the other way around: it would clear every finding instead."""
    with pytest.raises(ValueError, match="No packages"):
        audit_status(
            audit_report("aiohttp==3.14.3"),
            "aiohttp==3.14.3",
            BASE_CLOSURE,
            '{"packages": [{"name": "aiohttp"}]}',
        )


def test_findings_without_a_target_branch_set_compare_changed_requirements() -> None:
    """Resolving the target branch can fail; the changed requirements remain a usable basis."""
    assert audit_status(audit_report("aiohttp"), "some-pkg==1.0") == "preexisting"
    assert audit_status(audit_report("aiohttp"), "aiohttp==3.14.1") == "fail"


def test_findings_without_dependency_changes_are_preexisting() -> None:
    """A pull request that changes no dependency can never introduce a vulnerability."""
    assert audit_status(audit_report("aiohttp"), "") == "preexisting"


def test_findings_match_across_name_spellings() -> None:
    """The comparison survives the underscore/dash spellings both sides use."""
    assert audit_status(audit_report("aiohttp_fast_zlib"), "aiohttp-fast-zlib==0.3.0") == "fail"


def test_main_prints_status(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """The status is printed for the reporting workflow to pick up."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp==3.14.3"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("aiohttp==3.14.3\n")
    base_closure = tmp_path / "base_closure.txt"
    base_closure.write_text(BASE_CLOSURE)

    assert main([str(audit), str(requirements), str(base_closure)]) == 0
    assert capsys.readouterr().out.strip() == "fail"


def test_main_reads_the_resolutions_in_order(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The target branch is the third argument, the pull request's own set the fourth."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp==3.14.1"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("music-assistant-models==1.1.183\n")
    without = tmp_path / "without.txt"
    without.write_text("aiohttp==3.14.3\n")
    carrying = tmp_path / "carrying.txt"
    carrying.write_text("aiohttp==3.14.1\n")

    assert main([str(audit), str(requirements), str(without), str(carrying)]) == 0
    assert capsys.readouterr().out.strip() == "fail"

    assert main([str(audit), str(requirements), str(carrying), str(without)]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


def test_main_keeps_the_status_alone_on_stdout(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The workflow captures stdout into its status variable, so the note goes to stderr."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp==3.14.1"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("music-assistant-models==1.1.183\n")
    closure = tmp_path / "closure.txt"
    closure.write_text("aiohttp==3.14.3\nclean-package==1.0.0\n")

    assert main([str(audit), str(requirements), str(closure), str(closure)]) == 0
    captured = capsys.readouterr()
    assert captured.out == "preexisting\n"
    assert "`aiohttp 3.14.1` (resolved to 3.14.3)" in captured.err


def test_main_without_a_base_closure_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The resolved set is absent when the target branch could not be resolved."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("transformers==5.14.1"))
    requirements = tmp_path / "new_deps.txt"
    requirements.write_text("beat-this==1.1.0\n")

    assert main([str(audit), str(requirements), str(tmp_path / "missing.txt")]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


def test_main_with_an_empty_base_closure_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """An empty resolved set carries no comparison and must not raise."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("transformers==5.14.1"))
    base_closure = tmp_path / "base_closure.txt"
    base_closure.write_text("")

    assert main([str(audit), str(tmp_path / "missing.txt"), str(base_closure)]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


def test_main_without_a_requirements_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The requirements file is absent when the analysis found no dependency changes."""
    audit = tmp_path / "audit.json"
    audit.write_text(audit_report("aiohttp"))

    assert main([str(audit), str(tmp_path / "missing.txt")]) == 0
    assert capsys.readouterr().out.strip() == "preexisting"


@pytest.mark.parametrize(
    ("report", "expected"),
    [
        ("not json at all", json.JSONDecodeError),
        # A pip-audit release that renames the key must not read as "no findings"
        ('{"deps": [], "fixes": []}', KeyError),
    ],
)
def test_an_unusable_report_raises(tmp_path: Path, report: str, expected: type[Exception]) -> None:
    """An unreadable audit must fail loudly; the workflow gates on a non-zero exit."""
    audit = tmp_path / "audit.json"
    audit.write_text(report)

    with pytest.raises(expected):
        main([str(audit), str(tmp_path / "missing.txt")])


def test_a_missing_report_raises(tmp_path: Path) -> None:
    """pip-audit writing no report at all must fail loudly rather than pass."""
    with pytest.raises(FileNotFoundError):
        main([str(tmp_path / "missing.json"), str(tmp_path / "missing.txt")])
