"""Tests for the manifest back-sync helper used on Dependabot PRs."""

import json
from pathlib import Path

from scripts.sync_manifest_from_requirements import (
    _package_name,
    _parse_requirements_all,
    _sync_manifest,
)


def _write_manifest(tmp_path: Path, requirements: list[str]) -> Path:
    """Write a minimal manifest.json with the given requirements and return its path."""
    manifest = {
        "type": "player",
        "domain": "demo",
        "name": "Demo",
        "description": "A demo provider.",
        "codeowners": ["@octocat"],
        "requirements": requirements,
    }
    path = tmp_path / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def test_package_name_handles_casing_extras_and_separators() -> None:
    """Distribution names are normalized; git/URL specs return None."""
    assert _package_name("PyChromecast==14.0.10") == "pychromecast"
    assert _package_name("gql[all]==4.0.0") == "gql"
    assert _package_name("aiohttp_fast_zlib==0.3.0") == "aiohttp-fast-zlib"
    # PEP 503: dot/underscore/dash all collapse to a single dash.
    assert _package_name("niconico.py-ma==1.0.0") == "niconico-py-ma"
    assert _package_name("git+https://example.com/foo.git") is None


def test_parse_requirements_all_skips_directives_and_synthesized_lines() -> None:
    """Synthesized platform_machine entries are ignored, but other PEP 508 markers are kept."""
    content = (
        "# WARNING: this file is autogenerated!\n\n"
        "--extra-index-url https://download.pytorch.org/whl/cpu\n\n"
        "srptools>=1.0.0\n"
        "torch==2.3.0+cpu; sys_platform == 'linux' and platform_machine == 'x86_64'\n"
        "torch==2.3.0; sys_platform != 'linux' or platform_machine != 'x86_64'\n"
        "foo==1.0; python_version < '3.13'\n"
    )
    wanted = _parse_requirements_all(content)
    assert wanted == {
        "srptools": "srptools>=1.0.0",
        "foo": "foo==1.0; python_version < '3.13'",
    }


def test_sync_updates_matching_requirement(tmp_path: Path) -> None:
    """A bumped pin is written into the manifest, preserving the other requirements verbatim."""
    manifest = _write_manifest(tmp_path, ["srptools>=1.0.0", "PyChromecast==14.0.10"])
    changes = _sync_manifest(manifest, {"srptools": "srptools>=1.0.1"})
    assert any("srptools>=1.0.0 -> srptools>=1.0.1" in change for change in changes)
    requirements = json.loads(manifest.read_text())["requirements"]
    assert requirements == ["srptools>=1.0.1", "PyChromecast==14.0.10"]


def test_sync_is_noop_when_already_in_sync(tmp_path: Path) -> None:
    """A manifest already matching requirements_all.txt is left untouched."""
    manifest = _write_manifest(tmp_path, ["srptools>=1.0.1"])
    before = manifest.read_text()
    assert _sync_manifest(manifest, {"srptools": "srptools>=1.0.1"}) == []
    assert manifest.read_text() == before
